// Generated by CIRCT firtool-1.75.0
module ChipyardPRCICtrlClockSinkDomain(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input  auto_resetSynchronizer_in_member_allClocks_fbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  auto_resetSynchronizer_in_member_allClocks_fbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  auto_resetSynchronizer_in_member_allClocks_uncore_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  auto_resetSynchronizer_in_member_allClocks_uncore_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_resetSynchronizer_out_member_allClocks_fbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_resetSynchronizer_out_member_allClocks_fbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_resetSynchronizer_out_member_allClocks_uncore_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output auto_resetSynchronizer_out_member_allClocks_uncore_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  ClockGroupResetSynchronizer resetSynchronizer (	// @[generators/rocket-chip/src/main/scala/prci/ResetSynchronizer.scala:46:69]
    .auto_in_member_allClocks_fbus_0_clock  (auto_resetSynchronizer_in_member_allClocks_fbus_0_clock),
    .auto_in_member_allClocks_fbus_0_reset  (auto_resetSynchronizer_in_member_allClocks_fbus_0_reset),
    .auto_in_member_allClocks_uncore_clock  (auto_resetSynchronizer_in_member_allClocks_uncore_clock),
    .auto_in_member_allClocks_uncore_reset  (auto_resetSynchronizer_in_member_allClocks_uncore_reset),
    .auto_out_member_allClocks_fbus_0_clock (auto_resetSynchronizer_out_member_allClocks_fbus_0_clock),
    .auto_out_member_allClocks_fbus_0_reset (auto_resetSynchronizer_out_member_allClocks_fbus_0_reset),
    .auto_out_member_allClocks_uncore_clock (auto_resetSynchronizer_out_member_allClocks_uncore_clock),
    .auto_out_member_allClocks_uncore_reset (auto_resetSynchronizer_out_member_allClocks_uncore_reset)
  );	// @[generators/rocket-chip/src/main/scala/prci/ResetSynchronizer.scala:46:69]
endmodule

