// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module CMP(	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
  input         clock,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
  input         reset,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
  input         io_d_input_bits_sign,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  input  [7:0]  io_d_input_bits_exp,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  input  [22:0] io_d_input_bits_mantissa,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  output        io_d_output_valid,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  output        io_d_output_bits_sign,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  output [7:0]  io_d_output_bits_exp,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  output [22:0] io_d_output_bits_mantissa,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  input         io_in_ctrl_valid,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  input  [2:0]  io_in_ctrl_bits_cmd,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  output        io_out_ctrl_valid,	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
  output [2:0]  io_out_ctrl_bits_cmd	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
);

  wire             _cmpUnit_io_out_max_sign;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  wire [7:0]       _cmpUnit_io_out_max_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  wire [22:0]      _cmpUnit_io_out_max_mantissa;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  wire             _cmpUnit_io_out_diff_sign;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  wire [7:0]       _cmpUnit_io_out_diff_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  wire [22:0]      _cmpUnit_io_out_diff_mantissa;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  wire [7:0][22:0] _GEN = '{23'h5CAE0F, 23'h640507, 23'h6AE156, 23'h711D65, 23'h768DCF, 23'h7B00A2, 23'h7E3C91, 23'h0};
  wire [7:0][7:0]  _GEN_0 = '{8'hE, 8'hC, 8'hA, 8'h8, 8'h6, 8'h4, 8'h2, 8'h1};
  reg              oldMax_sign;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
  reg  [7:0]       oldMax_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
  reg  [22:0]      oldMax_mantissa;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
  reg              newMax_sign;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
  reg  [7:0]       newMax_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
  reg  [22:0]      newMax_mantissa;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
  wire             update_new_max = io_in_ctrl_bits_cmd == 3'h0;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:37:28]
  wire             prop_new_max = io_in_ctrl_bits_cmd == 3'h1;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:38:26]
  wire             prop_zero = io_in_ctrl_bits_cmd == 3'h3;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:40:23]
  wire             prop_exp2_intercepts = io_in_ctrl_bits_cmd == 3'h5;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:42:34]
  reg  [2:0]       exp2_counter_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  wire             _GEN_1 = prop_zero | prop_exp2_intercepts;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:40:23, :42:34, :58:26]
  wire             downCastDIn_rawA_isZero = io_d_input_bits_exp == 8'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:25]
  wire             downCastDIn_rawA_isInf = (&io_d_input_bits_exp) & ~(|io_d_input_bits_mantissa);	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,29,32,51}]
  wire             downCastDIn_rawA_isNaN = (&io_d_input_bits_exp) & (|io_d_input_bits_mantissa);	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,51}, :26:29]
  wire [8:0]       _downCastDIn_rawA_exp_T_1 = {1'h0, io_d_input_bits_exp} - 9'h7F;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:27]
  wire [7:0]       downCastDIn_roundedMantissa = {1'h0, io_d_input_bits_mantissa[22:16]} + {7'h0, io_d_input_bits_mantissa[15] & (|(io_d_input_bits_mantissa[14:0])) | io_d_input_bits_mantissa[15] & ~(|(io_d_input_bits_mantissa[14:0])) & io_d_input_bits_mantissa[16]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:24:{44,52}, :25:28, :26:{30,60}, :27:{35,65}, :30:{27,38,44,47,55}, :36:43]
  wire [9:0]       downCastDIn_roundedExp = {_downCastDIn_rawA_exp_T_1[8], _downCastDIn_rawA_exp_T_1} + {9'h0, downCastDIn_roundedMantissa[7]};	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:27, generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:{30,53}]
  wire             downCastDIn_overflow = $signed(downCastDIn_roundedExp) > 10'sh7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31]
  wire             downCastDIn_underflow = $signed(downCastDIn_roundedExp) < -10'sh7E;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :41:32]
  wire             do_reset = io_in_ctrl_bits_cmd == 3'h4;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:41:22]
  wire             _GEN_2 = _GEN_1 | io_in_ctrl_bits_cmd != 3'h2;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23, :39:23, :58:{26,51}, :62:23]
  always @(posedge clock) begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
    if (reset) begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
      oldMax_sign <= 1'h1;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
      oldMax_exp <= 8'hFF;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
      oldMax_mantissa <= 23'h0;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
      newMax_sign <= 1'h1;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
      newMax_exp <= 8'hFF;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
      newMax_mantissa <= 23'h0;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
      exp2_counter_value <= 3'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
    end
    else begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
      if (io_in_ctrl_valid) begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:24:14]
        oldMax_sign <= do_reset | (_GEN_2 ? oldMax_sign : _cmpUnit_io_out_max_sign);	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23, :33:23, :41:22, :55:20, :57:14, :58:51, :62:23]
        if (do_reset) begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:41:22]
          oldMax_exp <= 8'hFF;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
          oldMax_mantissa <= 23'h0;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23]
          newMax_exp <= 8'hFF;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
          newMax_mantissa <= 23'h0;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
        end
        else begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:41:22]
          if (_GEN_2) begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23, :58:51, :62:23]
          end
          else begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23, :58:51, :62:23]
            oldMax_exp <= _cmpUnit_io_out_max_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23, :33:23]
            oldMax_mantissa <= _cmpUnit_io_out_max_mantissa;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23, :33:23]
          end
          if (~_GEN_1) begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:58:26, :69:26, :71:8]
            newMax_exp <= _cmpUnit_io_out_max_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23, :34:23]
            newMax_mantissa <= _cmpUnit_io_out_max_mantissa;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23, :34:23]
          end
        end
        newMax_sign <= do_reset | (_GEN_1 ? newMax_sign : _cmpUnit_io_out_max_sign);	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23, :34:23, :41:22, :55:20, :56:14, :58:{26,51}, :61:14]
      end
      if (io_in_ctrl_valid & prop_exp2_intercepts)	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:42:34, :50:24]
        exp2_counter_value <= exp2_counter_value + 3'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
    initial begin	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
        `INIT_RANDOM_PROLOG_	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
        end	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
        oldMax_sign = _RANDOM[2'h0][0];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :33:23]
        oldMax_exp = _RANDOM[2'h0][8:1];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :33:23]
        oldMax_mantissa = _RANDOM[2'h0][31:9];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :33:23]
        newMax_sign = _RANDOM[2'h1][0];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :34:23]
        newMax_exp = _RANDOM[2'h1][8:1];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :34:23]
        newMax_mantissa = _RANDOM[2'h1][31:9];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :34:23]
        exp2_counter_value = _RANDOM[2'h2][2:0];	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, src/main/scala/chisel3/util/Counter.scala:61:40]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  FPCmpUnit cmpUnit (	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
    .io_in_a_sign         (update_new_max ? io_d_input_bits_sign : ~prop_new_max & oldMax_sign),	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23, :37:28, :38:26, :45:{25,62}]
    .io_in_a_exp          (update_new_max ? io_d_input_bits_exp : prop_new_max ? 8'h0 : oldMax_exp),	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23, :37:28, :38:26, :45:{25,62}]
    .io_in_a_mantissa     (update_new_max ? io_d_input_bits_mantissa : prop_new_max ? 23'h0 : oldMax_mantissa),	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:33:23, :37:28, :38:26, :45:{25,62}]
    .io_in_b_sign         (newMax_sign),	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
    .io_in_b_exp          (newMax_exp),	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
    .io_in_b_mantissa     (newMax_mantissa),	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:34:23]
    .io_out_max_sign      (_cmpUnit_io_out_max_sign),
    .io_out_max_exp       (_cmpUnit_io_out_max_exp),
    .io_out_max_mantissa  (_cmpUnit_io_out_max_mantissa),
    .io_out_diff_sign     (_cmpUnit_io_out_diff_sign),
    .io_out_diff_exp      (_cmpUnit_io_out_diff_exp),
    .io_out_diff_mantissa (_cmpUnit_io_out_diff_mantissa)
  );	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:31:23]
  assign io_d_output_valid = io_in_ctrl_valid & io_in_ctrl_bits_cmd != 3'h4;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :41:22, :79:{41,44}]
  assign io_d_output_bits_sign = ~_GEN_1 & ~update_new_max & _cmpUnit_io_out_diff_sign;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :31:23, :37:28, :58:26, :69:26, :71:8, :73:10]
  assign io_d_output_bits_exp = prop_zero ? 8'h0 : prop_exp2_intercepts ? _GEN_0[exp2_counter_value] : update_new_max ? 8'h0 : _cmpUnit_io_out_diff_exp;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :31:23, :37:28, :40:23, :42:34, :69:26, :71:8, :73:10, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_d_output_bits_mantissa = prop_zero ? 23'h0 : prop_exp2_intercepts ? _GEN[exp2_counter_value] : update_new_max ? {7'h0, io_d_input_bits_sign & ~downCastDIn_rawA_isNaN, downCastDIn_rawA_isInf | downCastDIn_rawA_isNaN | downCastDIn_overflow ? 8'hFF : downCastDIn_rawA_isZero | downCastDIn_underflow ? 8'h0 : downCastDIn_roundedExp[7:0] + 8'h7F, downCastDIn_rawA_isNaN ? 7'h40 : downCastDIn_rawA_isZero | downCastDIn_rawA_isInf | downCastDIn_underflow | downCastDIn_overflow ? 7'h0 : downCastDIn_roundedMantissa[6:0]} : _cmpUnit_io_out_diff_mantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:25, :25:29, :26:29, generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:30, :40:31, :41:32, :42:{28,31}, :43:{21,32,45}, :45:{10,22}, :47:28, :50:26, :52:{10,22,35,48}, :54:29, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:161:75, generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7, :31:23, :37:28, :40:23, :42:34, :69:26, :71:8, :73:10, src/main/scala/chisel3/util/Counter.scala:61:40]
  assign io_out_ctrl_valid = io_in_ctrl_valid;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
  assign io_out_ctrl_bits_cmd = io_in_ctrl_bits_cmd;	// @[generators/fsa/src/main/scala/fsa/sa/CMP.scala:22:7]
endmodule

