// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Ehr(	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
  input  clock,	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
  input  reset,	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
  output io_read_1,	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:9:14]
  input  io_write_0_valid,	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:9:14]
  input  io_write_1_valid	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:9:14]
);

  reg reg_0;	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:14:34]
  always @(posedge clock) begin	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
    if (reset)	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
      reg_0 <= 1'h0;	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7, :14:34]
    else if (io_write_1_valid ? io_write_1_valid : io_write_0_valid)	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:22:45]
      reg_0 <= ~io_write_1_valid;	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:9:14, :14:34, :22:45]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
    initial begin	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
        `INIT_RANDOM_PROLOG_	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
        reg_0 = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7, :14:34]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_read_1 = io_write_0_valid | reg_0;	// @[generators/fsa/src/main/scala/fsa/utils/Ehr.scala:7:7, :14:34, :18:13]
endmodule

