// Generated by CIRCT firtool-1.75.0
module FMA(	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:120:7]
  input  [31:0] io_a,	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:126:14]
  input  [31:0] io_c,	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:126:14]
  output [31:0] io_out	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:126:14]
);

  wire        _rawFMA_io_out_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  wire        _rawFMA_io_out_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  wire        _rawFMA_io_out_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  wire        _rawFMA_io_out_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  wire [10:0] _rawFMA_io_out_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  wire [25:0] _rawFMA_io_out_mantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  wire [23:0] io_out_roundedMantissa = {1'h0, _rawFMA_io_out_mantissa[24:2]} + {23'h0, _rawFMA_io_out_mantissa[1] & _rawFMA_io_out_mantissa[0] | _rawFMA_io_out_mantissa[1] & ~(_rawFMA_io_out_mantissa[0]) & _rawFMA_io_out_mantissa[2]};	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22, generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:24:{44,52}, :25:28, :26:{30,60}, :27:35, :30:{27,38,44,47,55}, :36:43]
  wire [11:0] io_out_roundedExp = {_rawFMA_io_out_exp[10], _rawFMA_io_out_exp} + {11'h0, io_out_roundedMantissa[23]};	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22, generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:{30,53}]
  wire        io_out_overflow = $signed(io_out_roundedExp) > 12'sh7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31]
  wire        io_out_underflow = $signed(io_out_roundedExp) < -12'sh7E;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :41:32]
  RawFloat_FMA rawFMA (	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
    .io_a_isZero     (io_a[30:23] == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:25]
    .io_a_isInf      ((&(io_a[30:23])) & ~(|(io_a[22:0]))),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,29,32,51}]
    .io_a_isNaN      ((&(io_a[30:23])) & (|(io_a[22:0]))),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,51}, :26:29]
    .io_a_sign       (io_a[31]),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:19]
    .io_a_exp        ({1'h0, io_a[30:23]} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:27]
    .io_a_mantissa   ({1'h1, io_a[22:0]}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:22:35, :34:28]
    .io_b_isZero     (1'h0),
    .io_b_isInf      (1'h0),
    .io_b_isNaN      (1'h0),
    .io_b_sign       (1'h0),
    .io_b_exp        (9'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
    .io_b_mantissa   (24'h800000),	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
    .io_c_isZero     (io_c[30:23] == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:25]
    .io_c_isInf      ((&(io_c[30:23])) & ~(|(io_c[22:0]))),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,29,32,51}]
    .io_c_isNaN      ((&(io_c[30:23])) & (|(io_c[22:0]))),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,51}, :26:29]
    .io_c_sign       (io_c[31]),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:19]
    .io_c_exp        ({1'h0, io_c[30:23]} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:27]
    .io_c_mantissa   ({1'h1, io_c[22:0]}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:22:35, :34:28]
    .io_out_isZero   (_rawFMA_io_out_isZero),
    .io_out_isInf    (_rawFMA_io_out_isInf),
    .io_out_isNaN    (_rawFMA_io_out_isNaN),
    .io_out_sign     (_rawFMA_io_out_sign),
    .io_out_exp      (_rawFMA_io_out_exp),
    .io_out_mantissa (_rawFMA_io_out_mantissa)
  );	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:133:22]
  assign io_out = {_rawFMA_io_out_sign & ~_rawFMA_io_out_isNaN, _rawFMA_io_out_isInf | _rawFMA_io_out_isNaN | io_out_overflow ? 8'hFF : _rawFMA_io_out_isZero | io_out_underflow ? 8'h0 : io_out_roundedExp[7:0] + 8'h7F, _rawFMA_io_out_isNaN ? 23'h400000 : _rawFMA_io_out_isZero | _rawFMA_io_out_isInf | io_out_underflow | io_out_overflow ? 23'h0 : io_out_roundedMantissa[22:0]};	// @[generators/easyfloat/src/main/scala/easyfloat/FMA.scala:120:7, :133:22, generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:30, :40:31, :41:32, :42:{28,31}, :43:{21,32,45}, :45:{10,22}, :47:28, :50:26, :52:{10,22,35,48}, :54:29, :57:23]
endmodule

