// Generated by CIRCT firtool-1.75.0
module FPAccUnit(	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:44:7]
  input         clock,	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:44:7]
  input         reset,	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:44:7]
  input         io_in_a_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [7:0]  io_in_a_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [22:0] io_in_a_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         io_in_b_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [7:0]  io_in_b_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [22:0] io_in_b_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         io_in_c_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [7:0]  io_in_c_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [22:0] io_in_c_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         io_in_cmd,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output        io_out_accType_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output [7:0]  io_out_accType_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output [22:0] io_out_accType_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         multiCycleIO_reciprocal_in_valid,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:97:24]
  output        multiCycleIO_reciprocal_out_valid	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:97:24]
);

  wire        _reciprocal_io_fma_rawA_isZero;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawA_isInf;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawA_isNaN;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawA_sign;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire [8:0]  _reciprocal_io_fma_rawA_exp;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire [23:0] _reciprocal_io_fma_rawA_mantissa;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawB_isZero;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawB_isInf;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawB_isNaN;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawB_sign;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire [8:0]  _reciprocal_io_fma_rawB_exp;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire [23:0] _reciprocal_io_fma_rawB_mantissa;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _reciprocal_io_fma_rawC_isZero;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire [8:0]  _reciprocal_io_fma_rawC_exp;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire [23:0] _reciprocal_io_fma_rawC_mantissa;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  wire        _mulAddExp2_io_out_isZero;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire        _mulAddExp2_io_out_isInf;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire        _mulAddExp2_io_out_isNaN;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire        _mulAddExp2_io_out_sign;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire [10:0] _mulAddExp2_io_out_exp;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire [25:0] _mulAddExp2_io_out_mantissa;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire [23:0] io_out_accType_roundedMantissa = {1'h0, _mulAddExp2_io_out_mantissa[24:2]} + {23'h0, _mulAddExp2_io_out_mantissa[1] & _mulAddExp2_io_out_mantissa[0] | _mulAddExp2_io_out_mantissa[1] & ~(_mulAddExp2_io_out_mantissa[0]) & _mulAddExp2_io_out_mantissa[2]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:24:{44,52}, :25:28, :26:{30,60}, :27:35, :30:{27,38,44,47,55}, :36:43, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire [11:0] io_out_accType_roundedExp = {_mulAddExp2_io_out_exp[10], _mulAddExp2_io_out_exp} + {11'h0, io_out_accType_roundedMantissa[23]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:{30,53}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire        io_out_accType_overflow = $signed(io_out_accType_roundedExp) > 12'sh7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31]
  wire        io_out_accType_underflow = $signed(io_out_accType_roundedExp) < -12'sh7E;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :41:32]
  wire        io_out_accType_resSign = _mulAddExp2_io_out_sign & ~_mulAddExp2_io_out_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:42:{28,31}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire [7:0]  io_out_accType_resExp = _mulAddExp2_io_out_isInf | _mulAddExp2_io_out_isNaN | io_out_accType_overflow ? 8'hFF : _mulAddExp2_io_out_isZero | io_out_accType_underflow ? 8'h0 : io_out_accType_roundedExp[7:0] + 8'h7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31, :41:32, :43:{21,32,45}, :45:{10,22}, :47:28, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  wire [22:0] io_out_accType_resMantissa = _mulAddExp2_io_out_isNaN ? 23'h400000 : _mulAddExp2_io_out_isZero | _mulAddExp2_io_out_isInf | io_out_accType_underflow | io_out_accType_overflow ? 23'h0 : io_out_accType_roundedMantissa[22:0];	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :40:31, :41:32, :50:26, :52:{10,22,35,48}, :54:29, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  RawFloat_MulAddExp2_1 mulAddExp2 (	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
    .io_in_exp2       (~multiCycleIO_reciprocal_in_valid & io_in_cmd),	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:64:{28,52}]
    .io_in_a_isZero   (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_isZero : io_in_a_exp == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:{12,25}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :66:24]
    .io_in_a_isInf    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_isInf : (&io_in_a_exp) & ~(|io_in_a_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{11,24,29,32,51}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :66:24]
    .io_in_a_isNaN    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_isNaN : (&io_in_a_exp) & (|io_in_a_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,51}, :26:{11,29}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :66:24]
    .io_in_a_sign     (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_sign : io_in_a_sign),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:10, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :66:24]
    .io_in_a_exp      (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_exp : {1'h0, io_in_a_exp} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:{9,27}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :66:24]
    .io_in_a_mantissa (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_mantissa : {1'h1, io_in_a_mantissa}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:34:{16,28}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :66:24]
    .io_in_b_isZero   (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_isZero : io_in_b_exp == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:{12,25}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :67:24]
    .io_in_b_isInf    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_isInf : (&io_in_b_exp) & ~(|io_in_b_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{11,24,29,32,51}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :67:24]
    .io_in_b_isNaN    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_isNaN : (&io_in_b_exp) & (|io_in_b_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,51}, :26:{11,29}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :67:24]
    .io_in_b_sign     (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_sign : io_in_b_sign),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:10, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :67:24]
    .io_in_b_exp      (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_exp : {1'h0, io_in_b_exp} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:{9,27}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :67:24]
    .io_in_b_mantissa (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_mantissa : {1'h1, io_in_b_mantissa}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:34:{16,28}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :67:24]
    .io_in_c_isZero   (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawC_isZero : io_in_c_exp == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:{12,25}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :68:24]
    .io_in_c_isInf    (~multiCycleIO_reciprocal_in_valid & (&io_in_c_exp) & ~(|io_in_c_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{11,24,29,32,51}, :28:10, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:65:32, :68:24]
    .io_in_c_isNaN    (~multiCycleIO_reciprocal_in_valid & (&io_in_c_exp) & (|io_in_c_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,51}, :26:{11,29}, :28:10, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:65:32, :68:24]
    .io_in_c_sign     (~multiCycleIO_reciprocal_in_valid & io_in_c_sign),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:10, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:65:32, :68:24]
    .io_in_c_exp      (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawC_exp : {1'h0, io_in_c_exp} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:{9,27}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :68:24]
    .io_in_c_mantissa (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawC_mantissa : {1'h1, io_in_c_mantissa}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:34:{16,28}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26, :65:32, :68:24]
    .io_out_isZero    (_mulAddExp2_io_out_isZero),
    .io_out_isInf     (_mulAddExp2_io_out_isInf),
    .io_out_isNaN     (_mulAddExp2_io_out_isNaN),
    .io_out_sign      (_mulAddExp2_io_out_sign),
    .io_out_exp       (_mulAddExp2_io_out_exp),
    .io_out_mantissa  (_mulAddExp2_io_out_mantissa)
  );	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:52:26]
  Reciprocal reciprocal (	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
    .clock                 (clock),
    .reset                 (reset),
    .io_in                 ({io_in_a_sign, io_in_a_exp, io_in_a_mantissa}),	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:61:31]
    .io_in_valid           (multiCycleIO_reciprocal_in_valid),
    .io_out_valid          (multiCycleIO_reciprocal_out_valid),
    .io_fma_rawA_isZero    (_reciprocal_io_fma_rawA_isZero),
    .io_fma_rawA_isInf     (_reciprocal_io_fma_rawA_isInf),
    .io_fma_rawA_isNaN     (_reciprocal_io_fma_rawA_isNaN),
    .io_fma_rawA_sign      (_reciprocal_io_fma_rawA_sign),
    .io_fma_rawA_exp       (_reciprocal_io_fma_rawA_exp),
    .io_fma_rawA_mantissa  (_reciprocal_io_fma_rawA_mantissa),
    .io_fma_rawB_isZero    (_reciprocal_io_fma_rawB_isZero),
    .io_fma_rawB_isInf     (_reciprocal_io_fma_rawB_isInf),
    .io_fma_rawB_isNaN     (_reciprocal_io_fma_rawB_isNaN),
    .io_fma_rawB_sign      (_reciprocal_io_fma_rawB_sign),
    .io_fma_rawB_exp       (_reciprocal_io_fma_rawB_exp),
    .io_fma_rawB_mantissa  (_reciprocal_io_fma_rawB_mantissa),
    .io_fma_rawC_isZero    (_reciprocal_io_fma_rawC_isZero),
    .io_fma_rawC_exp       (_reciprocal_io_fma_rawC_exp),
    .io_fma_rawC_mantissa  (_reciprocal_io_fma_rawC_mantissa),
    .io_fma_rounded_result ({io_out_accType_resSign, io_out_accType_resExp, io_out_accType_resMantissa})	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:42:28, :43:21, :50:26, :57:23]
  );	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:60:26]
  assign io_out_accType_sign = io_out_accType_resSign;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:42:28, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:44:7]
  assign io_out_accType_exp = io_out_accType_resExp;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:43:21, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:44:7]
  assign io_out_accType_mantissa = io_out_accType_resMantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:50:26, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:44:7]
endmodule

