// Generated by CIRCT firtool-1.75.0
module FPCmpUnit(	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7]
  input         io_in_a_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  input  [7:0]  io_in_a_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  input  [22:0] io_in_a_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  input         io_in_b_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  input  [7:0]  io_in_b_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  input  [22:0] io_in_b_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  output        io_out_max_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  output [7:0]  io_out_max_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  output [22:0] io_out_max_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  output        io_out_diff_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  output [7:0]  io_out_diff_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
  output [22:0] io_out_diff_mantissa	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:88:14]
);

  wire [31:0] _fma_io_out;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:78:19]
  FMA fma (	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:78:19]
    .io_a   ({io_in_a_sign, io_in_a_exp, io_in_a_mantissa}),	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:82:23]
    .io_c   ({~io_in_b_sign, io_in_b_exp, io_in_b_mantissa}),	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:80:16, :84:20]
    .io_out (_fma_io_out)
  );	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:78:19]
  assign io_out_max_sign = _fma_io_out[31] ? io_in_b_sign : io_in_a_sign;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7, :78:19, :85:{16,36}]
  assign io_out_max_exp = _fma_io_out[31] ? io_in_b_exp : io_in_a_exp;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7, :78:19, :85:{16,36}]
  assign io_out_max_mantissa = _fma_io_out[31] ? io_in_b_mantissa : io_in_a_mantissa;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7, :78:19, :85:{16,36}]
  assign io_out_diff_sign = _fma_io_out[31];	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7, :78:19, :90:37]
  assign io_out_diff_exp = _fma_io_out[30:23];	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7, :78:19, :90:37]
  assign io_out_diff_mantissa = _fma_io_out[22:0];	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:77:7, :78:19, :90:37]
endmodule

