// Generated by CIRCT firtool-1.75.0
module FPMacUnit(	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7]
  input         io_in_a_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [7:0]  io_in_a_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [6:0]  io_in_a_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         io_in_b_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [7:0]  io_in_b_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [6:0]  io_in_b_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         io_in_c_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [7:0]  io_in_c_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input  [22:0] io_in_c_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  input         io_in_cmd,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output        io_out_accType_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output [7:0]  io_out_accType_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output [22:0] io_out_accType_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output        io_out_elemType_sign,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output [7:0]  io_out_elemType_exp,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output [6:0]  io_out_elemType_mantissa,	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
  output        io_out_exp2	// @[generators/fsa/src/main/scala/fsa/arithmetic/Arithmetic.scala:76:14]
);

  wire        _mulAddExp2_io_out_isZero;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire        _mulAddExp2_io_out_isInf;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire        _mulAddExp2_io_out_isNaN;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire        _mulAddExp2_io_out_sign;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [10:0] _mulAddExp2_io_out_exp;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [25:0] _mulAddExp2_io_out_mantissa;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [2:0]  _mulAddExp2_io_exp2_frac_msb;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [23:0] io_out_accType_roundedMantissa = {1'h0, _mulAddExp2_io_out_mantissa[24:2]} + {23'h0, _mulAddExp2_io_out_mantissa[1] & _mulAddExp2_io_out_mantissa[0] | _mulAddExp2_io_out_mantissa[1] & ~(_mulAddExp2_io_out_mantissa[0]) & _mulAddExp2_io_out_mantissa[2]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:24:{44,52}, :25:28, :26:{30,60}, :27:35, :30:{27,38,44,47,55}, :36:43, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [11:0] _GEN = {_mulAddExp2_io_out_exp[10], _mulAddExp2_io_out_exp};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [11:0] io_out_accType_roundedExp = _GEN + {11'h0, io_out_accType_roundedMantissa[23]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:{30,53}]
  wire        io_out_accType_overflow = $signed(io_out_accType_roundedExp) > 12'sh7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31]
  wire        io_out_accType_underflow = $signed(io_out_accType_roundedExp) < -12'sh7E;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :41:32]
  wire        _io_out_elemType_resExp_T = _mulAddExp2_io_out_isInf | _mulAddExp2_io_out_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:43:32, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire        _io_out_elemType_resMantissa_T = _mulAddExp2_io_out_isZero | _mulAddExp2_io_out_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:52:22, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [7:0]  io_out_elemType_roundedMantissa = {1'h0, _mulAddExp2_io_out_mantissa[24:18]} + {7'h0, _mulAddExp2_io_out_mantissa[17] & (|(_mulAddExp2_io_out_mantissa[16:0])) | _mulAddExp2_io_out_mantissa[17] & ~(|(_mulAddExp2_io_out_mantissa[16:0])) & _mulAddExp2_io_out_mantissa[18]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:24:{44,52}, :25:28, :26:{30,60}, :27:{35,65}, :30:{27,38,44,47,55}, :36:43, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  wire [11:0] io_out_elemType_roundedExp = _GEN + {11'h0, io_out_elemType_roundedMantissa[7]};	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :39:{30,53}]
  wire        io_out_elemType_overflow = $signed(io_out_elemType_roundedExp) > 12'sh7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31]
  wire        io_out_elemType_underflow = $signed(io_out_elemType_roundedExp) < -12'sh7E;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :41:32]
  RawFloat_MulAddExp2 mulAddExp2 (	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
    .io_in_exp2       (io_in_cmd),
    .io_in_a_isZero   (io_in_a_exp == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:25]
    .io_in_a_isInf    ((&io_in_a_exp) & ~(|io_in_a_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,29,32,51}]
    .io_in_a_isNaN    ((&io_in_a_exp) & (|io_in_a_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,51}, :26:29]
    .io_in_a_sign     (io_in_a_sign),
    .io_in_a_exp      ({1'h0, io_in_a_exp} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:27]
    .io_in_a_mantissa ({1'h1, io_in_a_mantissa}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:34:28]
    .io_in_b_isZero   (io_in_b_exp == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:25]
    .io_in_b_isInf    ((&io_in_b_exp) & ~(|io_in_b_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,29,32,51}]
    .io_in_b_isNaN    ((&io_in_b_exp) & (|io_in_b_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:25:{24,51}, :26:29]
    .io_in_b_sign     (io_in_b_sign),
    .io_in_b_exp      ({1'h0, io_in_b_exp} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:27]
    .io_in_b_mantissa ({1'h1, io_in_b_mantissa}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:34:28]
    .io_in_c_isZero   (~io_in_cmd & io_in_c_exp == 8'h0),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:{12,25}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:28:31]
    .io_in_c_isInf    (~io_in_cmd & (&io_in_c_exp) & ~(|io_in_c_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:12, :25:{11,24,29,32,51}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:28:31]
    .io_in_c_isNaN    (~io_in_cmd & (&io_in_c_exp) & (|io_in_c_mantissa)),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:12, :25:{24,51}, :26:{11,29}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:28:31]
    .io_in_c_sign     (io_in_c_sign),
    .io_in_c_exp      (io_in_cmd ? {8'h3F, io_in_c_exp[0]} - 9'h7F : {1'h0, io_in_c_exp} - 9'h7F),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:29:{9,27}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:28:31, :32:52]
    .io_in_c_mantissa ({1'h1, io_in_c_mantissa}),	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:34:{16,28}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:28:31]
    .io_out_isZero    (_mulAddExp2_io_out_isZero),
    .io_out_isInf     (_mulAddExp2_io_out_isInf),
    .io_out_isNaN     (_mulAddExp2_io_out_isNaN),
    .io_out_sign      (_mulAddExp2_io_out_sign),
    .io_out_exp       (_mulAddExp2_io_out_exp),
    .io_out_mantissa  (_mulAddExp2_io_out_mantissa),
    .io_exp2_frac_msb (_mulAddExp2_io_exp2_frac_msb)
  );	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:21:26]
  assign io_out_accType_sign = _mulAddExp2_io_out_sign & ~_mulAddExp2_io_out_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:42:{28,31}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26]
  assign io_out_accType_exp = _io_out_elemType_resExp_T | io_out_accType_overflow ? 8'hFF : _mulAddExp2_io_out_isZero | io_out_accType_underflow ? 8'h0 : io_out_accType_roundedExp[7:0] + 8'h7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31, :41:32, :43:{21,32,45}, :45:{10,22}, :47:28, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26]
  assign io_out_accType_mantissa = _mulAddExp2_io_out_isNaN ? 23'h400000 : _io_out_elemType_resMantissa_T | io_out_accType_underflow | io_out_accType_overflow ? 23'h0 : io_out_accType_roundedMantissa[22:0];	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :40:31, :41:32, :50:26, :52:{10,22,35,48}, :54:29, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26]
  assign io_out_elemType_sign = _mulAddExp2_io_out_sign & ~_mulAddExp2_io_out_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:42:{28,31}, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26]
  assign io_out_elemType_exp = _io_out_elemType_resExp_T | io_out_elemType_overflow ? 8'hFF : _mulAddExp2_io_out_isZero | io_out_elemType_underflow ? 8'h0 : io_out_elemType_roundedExp[7:0] + 8'h7F;	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:39:30, :40:31, :41:32, :43:{21,32,45}, :45:{10,22}, :47:28, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26]
  assign io_out_elemType_mantissa = _mulAddExp2_io_out_isNaN ? 7'h40 : _io_out_elemType_resMantissa_T | io_out_elemType_underflow | io_out_elemType_overflow ? 7'h0 : io_out_elemType_roundedMantissa[6:0];	// @[generators/easyfloat/src/main/scala/easyfloat/Rounding.scala:36:43, :40:31, :41:32, :50:26, :52:{10,22,35,48}, :54:29, generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26]
  assign io_out_exp2 = io_in_cmd & io_in_c_exp[3:1] == _mulAddExp2_io_exp2_frac_msb;	// @[generators/fsa/src/main/scala/fsa/arithmetic/FPArithmeticImpl.scala:18:7, :21:26, :35:43, :39:{40,52}]
endmodule

