// Generated by CIRCT firtool-1.75.0
module FrontBus(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_ridx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_a_widx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_ridx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_widx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_source_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_sink_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_ridx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_to_fsa_fsa_fbus_xing_out_d_widx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_ridx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_widx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_source_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_sink_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [15:0] auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fixedClockNode_anon_out_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fixedClockNode_anon_out_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fbus_clock_groups_in_member_fbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fbus_clock_groups_in_member_fbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_bus_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_bus_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_bus_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_bus_xing_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_bus_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_bus_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [14:0] auto_bus_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_bus_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_bus_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_bus_xing_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_bus_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_bus_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_bus_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_bus_xing_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_bus_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_bus_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_bus_xing_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_bus_xing_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_bus_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_bus_xing_out_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire        _coupler_to_fsa_auto_tl_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_fsa_auto_tl_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_fsa_auto_tl_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [1:0]  _coupler_to_fsa_auto_tl_in_d_bits_param;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_fsa_auto_tl_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [3:0]  _coupler_to_fsa_auto_tl_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_fsa_auto_tl_in_d_bits_sink;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_fsa_auto_tl_in_d_bits_denied;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [31:0] _coupler_to_fsa_auto_tl_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_fsa_auto_tl_in_d_bits_corrupt;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_param;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [3:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [15:0] _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_address;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [3:0]  _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_mask;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [31:0] _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_corrupt;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_from_port_named_serial_tl_0_in_auto_tl_out_d_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]  _buffer_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [2:0]  _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]  _buffer_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [1:0]  _buffer_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [31:0] _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _fbus_xbar_auto_anon_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [1:0]  _fbus_xbar_auto_anon_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [3:0]  _fbus_xbar_auto_anon_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [1:0]  _fbus_xbar_auto_anon_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [31:0] _fbus_xbar_auto_anon_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_out_1_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_1_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_1_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_1_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [3:0]  _fbus_xbar_auto_anon_out_1_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [15:0] _fbus_xbar_auto_anon_out_1_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [3:0]  _fbus_xbar_auto_anon_out_1_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [31:0] _fbus_xbar_auto_anon_out_1_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_out_1_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_out_1_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_out_0_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_0_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_0_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [2:0]  _fbus_xbar_auto_anon_out_0_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [3:0]  _fbus_xbar_auto_anon_out_0_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [14:0] _fbus_xbar_auto_anon_out_0_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [3:0]  _fbus_xbar_auto_anon_out_0_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire [31:0] _fbus_xbar_auto_anon_out_0_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_out_0_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fbus_xbar_auto_anon_out_0_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  wire        _fixedClockNode_auto_anon_out_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  wire        _fixedClockNode_auto_anon_out_0_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  FixedClockBroadcast_2 fixedClockNode (	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_clock    (auto_fbus_clock_groups_in_member_fbus_0_clock),
    .auto_anon_in_reset    (auto_fbus_clock_groups_in_member_fbus_0_reset),
    .auto_anon_out_1_clock (auto_fixedClockNode_anon_out_clock),
    .auto_anon_out_1_reset (auto_fixedClockNode_anon_out_reset),
    .auto_anon_out_0_clock (_fixedClockNode_auto_anon_out_0_clock),
    .auto_anon_out_0_reset (_fixedClockNode_auto_anon_out_0_reset)
  );	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  TLXbar_fbus_i1_o2_a16d32s4k2z3u fbus_xbar (	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .clock                          (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                          (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_a_ready           (_fbus_xbar_auto_anon_in_a_ready),
    .auto_anon_in_a_valid           (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_opcode     (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_param      (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_param),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_size       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_source     (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_address    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_address),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_mask       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_mask),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_data       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_a_bits_corrupt    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_corrupt),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_d_ready           (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_d_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_in_d_valid           (_fbus_xbar_auto_anon_in_d_valid),
    .auto_anon_in_d_bits_opcode     (_fbus_xbar_auto_anon_in_d_bits_opcode),
    .auto_anon_in_d_bits_param      (_fbus_xbar_auto_anon_in_d_bits_param),
    .auto_anon_in_d_bits_size       (_fbus_xbar_auto_anon_in_d_bits_size),
    .auto_anon_in_d_bits_source     (_fbus_xbar_auto_anon_in_d_bits_source),
    .auto_anon_in_d_bits_sink       (_fbus_xbar_auto_anon_in_d_bits_sink),
    .auto_anon_in_d_bits_denied     (_fbus_xbar_auto_anon_in_d_bits_denied),
    .auto_anon_in_d_bits_data       (_fbus_xbar_auto_anon_in_d_bits_data),
    .auto_anon_in_d_bits_corrupt    (_fbus_xbar_auto_anon_in_d_bits_corrupt),
    .auto_anon_out_1_a_ready        (_coupler_to_fsa_auto_tl_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_a_valid        (_fbus_xbar_auto_anon_out_1_a_valid),
    .auto_anon_out_1_a_bits_opcode  (_fbus_xbar_auto_anon_out_1_a_bits_opcode),
    .auto_anon_out_1_a_bits_param   (_fbus_xbar_auto_anon_out_1_a_bits_param),
    .auto_anon_out_1_a_bits_size    (_fbus_xbar_auto_anon_out_1_a_bits_size),
    .auto_anon_out_1_a_bits_source  (_fbus_xbar_auto_anon_out_1_a_bits_source),
    .auto_anon_out_1_a_bits_address (_fbus_xbar_auto_anon_out_1_a_bits_address),
    .auto_anon_out_1_a_bits_mask    (_fbus_xbar_auto_anon_out_1_a_bits_mask),
    .auto_anon_out_1_a_bits_data    (_fbus_xbar_auto_anon_out_1_a_bits_data),
    .auto_anon_out_1_a_bits_corrupt (_fbus_xbar_auto_anon_out_1_a_bits_corrupt),
    .auto_anon_out_1_d_ready        (_fbus_xbar_auto_anon_out_1_d_ready),
    .auto_anon_out_1_d_valid        (_coupler_to_fsa_auto_tl_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_opcode  (_coupler_to_fsa_auto_tl_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_param   (_coupler_to_fsa_auto_tl_in_d_bits_param),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_size    (_coupler_to_fsa_auto_tl_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_source  (_coupler_to_fsa_auto_tl_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_sink    (_coupler_to_fsa_auto_tl_in_d_bits_sink),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_denied  (_coupler_to_fsa_auto_tl_in_d_bits_denied),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_data    (_coupler_to_fsa_auto_tl_in_d_bits_data),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_1_d_bits_corrupt (_coupler_to_fsa_auto_tl_in_d_bits_corrupt),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_anon_out_0_a_ready        (_buffer_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_a_valid        (_fbus_xbar_auto_anon_out_0_a_valid),
    .auto_anon_out_0_a_bits_opcode  (_fbus_xbar_auto_anon_out_0_a_bits_opcode),
    .auto_anon_out_0_a_bits_param   (_fbus_xbar_auto_anon_out_0_a_bits_param),
    .auto_anon_out_0_a_bits_size    (_fbus_xbar_auto_anon_out_0_a_bits_size),
    .auto_anon_out_0_a_bits_source  (_fbus_xbar_auto_anon_out_0_a_bits_source),
    .auto_anon_out_0_a_bits_address (_fbus_xbar_auto_anon_out_0_a_bits_address),
    .auto_anon_out_0_a_bits_mask    (_fbus_xbar_auto_anon_out_0_a_bits_mask),
    .auto_anon_out_0_a_bits_data    (_fbus_xbar_auto_anon_out_0_a_bits_data),
    .auto_anon_out_0_a_bits_corrupt (_fbus_xbar_auto_anon_out_0_a_bits_corrupt),
    .auto_anon_out_0_d_ready        (_fbus_xbar_auto_anon_out_0_d_ready),
    .auto_anon_out_0_d_valid        (_buffer_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_opcode  (_buffer_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_param   (_buffer_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_size    (_buffer_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_source  (_buffer_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_sink    (_buffer_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_denied  (_buffer_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_data    (_buffer_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .auto_anon_out_0_d_bits_corrupt (_buffer_auto_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  TLBuffer_a15d32s4k2z3u buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .clock                   (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                   (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_a_valid         (_fbus_xbar_auto_anon_out_0_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_opcode   (_fbus_xbar_auto_anon_out_0_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_param    (_fbus_xbar_auto_anon_out_0_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_size     (_fbus_xbar_auto_anon_out_0_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_source   (_fbus_xbar_auto_anon_out_0_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_address  (_fbus_xbar_auto_anon_out_0_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_mask     (_fbus_xbar_auto_anon_out_0_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_data     (_fbus_xbar_auto_anon_out_0_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_a_bits_corrupt  (_fbus_xbar_auto_anon_out_0_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_d_ready         (_fbus_xbar_auto_anon_out_0_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (auto_bus_xing_out_a_ready),
    .auto_out_a_valid        (auto_bus_xing_out_a_valid),
    .auto_out_a_bits_opcode  (auto_bus_xing_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_bus_xing_out_a_bits_param),
    .auto_out_a_bits_size    (auto_bus_xing_out_a_bits_size),
    .auto_out_a_bits_source  (auto_bus_xing_out_a_bits_source),
    .auto_out_a_bits_address (auto_bus_xing_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_bus_xing_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_bus_xing_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_bus_xing_out_a_bits_corrupt),
    .auto_out_d_ready        (auto_bus_xing_out_d_ready),
    .auto_out_d_valid        (auto_bus_xing_out_d_valid),
    .auto_out_d_bits_opcode  (auto_bus_xing_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_bus_xing_out_d_bits_param),
    .auto_out_d_bits_size    (auto_bus_xing_out_d_bits_size),
    .auto_out_d_bits_source  (auto_bus_xing_out_d_bits_source),
    .auto_out_d_bits_sink    (auto_bus_xing_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_bus_xing_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_bus_xing_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_bus_xing_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  TLInterconnectCoupler_fbus_from_port_named_serial_tl_0_in coupler_from_port_named_serial_tl_0_in (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                         (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                         (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_buffer_in_a_ready        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_ready),
    .auto_buffer_in_a_valid        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_valid),
    .auto_buffer_in_a_bits_opcode  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_opcode),
    .auto_buffer_in_a_bits_param   (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_param),
    .auto_buffer_in_a_bits_size    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_size),
    .auto_buffer_in_a_bits_source  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_source),
    .auto_buffer_in_a_bits_address (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_address),
    .auto_buffer_in_a_bits_mask    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_mask),
    .auto_buffer_in_a_bits_data    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_data),
    .auto_buffer_in_a_bits_corrupt (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_a_bits_corrupt),
    .auto_buffer_in_d_ready        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_ready),
    .auto_buffer_in_d_valid        (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param   (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied  (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data    (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt (auto_coupler_from_port_named_serial_tl_0_in_buffer_in_d_bits_corrupt),
    .auto_tl_out_a_ready           (_fbus_xbar_auto_anon_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_a_valid           (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_valid),
    .auto_tl_out_a_bits_opcode     (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_opcode),
    .auto_tl_out_a_bits_param      (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_param),
    .auto_tl_out_a_bits_size       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_size),
    .auto_tl_out_a_bits_source     (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_source),
    .auto_tl_out_a_bits_address    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_address),
    .auto_tl_out_a_bits_mask       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_mask),
    .auto_tl_out_a_bits_data       (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_data),
    .auto_tl_out_a_bits_corrupt    (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_a_bits_corrupt),
    .auto_tl_out_d_ready           (_coupler_from_port_named_serial_tl_0_in_auto_tl_out_d_ready),
    .auto_tl_out_d_valid           (_fbus_xbar_auto_anon_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_opcode     (_fbus_xbar_auto_anon_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_param      (_fbus_xbar_auto_anon_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_size       (_fbus_xbar_auto_anon_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_source     (_fbus_xbar_auto_anon_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_sink       (_fbus_xbar_auto_anon_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_denied     (_fbus_xbar_auto_anon_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_data       (_fbus_xbar_auto_anon_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_out_d_bits_corrupt    (_fbus_xbar_auto_anon_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
  );	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  TLInterconnectCoupler_fbus_to_fsa coupler_to_fsa (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                        (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                        (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_fsa_fbus_xing_out_a_mem_0_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_opcode),
    .auto_fsa_fbus_xing_out_a_mem_0_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_param),
    .auto_fsa_fbus_xing_out_a_mem_0_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_size),
    .auto_fsa_fbus_xing_out_a_mem_0_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_source),
    .auto_fsa_fbus_xing_out_a_mem_0_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_address),
    .auto_fsa_fbus_xing_out_a_mem_0_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_mask),
    .auto_fsa_fbus_xing_out_a_mem_0_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_data),
    .auto_fsa_fbus_xing_out_a_mem_0_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_0_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_1_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_opcode),
    .auto_fsa_fbus_xing_out_a_mem_1_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_param),
    .auto_fsa_fbus_xing_out_a_mem_1_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_size),
    .auto_fsa_fbus_xing_out_a_mem_1_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_source),
    .auto_fsa_fbus_xing_out_a_mem_1_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_address),
    .auto_fsa_fbus_xing_out_a_mem_1_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_mask),
    .auto_fsa_fbus_xing_out_a_mem_1_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_data),
    .auto_fsa_fbus_xing_out_a_mem_1_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_1_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_2_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_opcode),
    .auto_fsa_fbus_xing_out_a_mem_2_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_param),
    .auto_fsa_fbus_xing_out_a_mem_2_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_size),
    .auto_fsa_fbus_xing_out_a_mem_2_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_source),
    .auto_fsa_fbus_xing_out_a_mem_2_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_address),
    .auto_fsa_fbus_xing_out_a_mem_2_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_mask),
    .auto_fsa_fbus_xing_out_a_mem_2_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_data),
    .auto_fsa_fbus_xing_out_a_mem_2_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_2_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_3_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_opcode),
    .auto_fsa_fbus_xing_out_a_mem_3_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_param),
    .auto_fsa_fbus_xing_out_a_mem_3_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_size),
    .auto_fsa_fbus_xing_out_a_mem_3_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_source),
    .auto_fsa_fbus_xing_out_a_mem_3_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_address),
    .auto_fsa_fbus_xing_out_a_mem_3_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_mask),
    .auto_fsa_fbus_xing_out_a_mem_3_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_data),
    .auto_fsa_fbus_xing_out_a_mem_3_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_3_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_4_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_opcode),
    .auto_fsa_fbus_xing_out_a_mem_4_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_param),
    .auto_fsa_fbus_xing_out_a_mem_4_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_size),
    .auto_fsa_fbus_xing_out_a_mem_4_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_source),
    .auto_fsa_fbus_xing_out_a_mem_4_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_address),
    .auto_fsa_fbus_xing_out_a_mem_4_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_mask),
    .auto_fsa_fbus_xing_out_a_mem_4_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_data),
    .auto_fsa_fbus_xing_out_a_mem_4_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_4_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_5_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_opcode),
    .auto_fsa_fbus_xing_out_a_mem_5_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_param),
    .auto_fsa_fbus_xing_out_a_mem_5_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_size),
    .auto_fsa_fbus_xing_out_a_mem_5_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_source),
    .auto_fsa_fbus_xing_out_a_mem_5_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_address),
    .auto_fsa_fbus_xing_out_a_mem_5_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_mask),
    .auto_fsa_fbus_xing_out_a_mem_5_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_data),
    .auto_fsa_fbus_xing_out_a_mem_5_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_5_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_6_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_opcode),
    .auto_fsa_fbus_xing_out_a_mem_6_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_param),
    .auto_fsa_fbus_xing_out_a_mem_6_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_size),
    .auto_fsa_fbus_xing_out_a_mem_6_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_source),
    .auto_fsa_fbus_xing_out_a_mem_6_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_address),
    .auto_fsa_fbus_xing_out_a_mem_6_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_mask),
    .auto_fsa_fbus_xing_out_a_mem_6_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_data),
    .auto_fsa_fbus_xing_out_a_mem_6_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_6_corrupt),
    .auto_fsa_fbus_xing_out_a_mem_7_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_opcode),
    .auto_fsa_fbus_xing_out_a_mem_7_param         (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_param),
    .auto_fsa_fbus_xing_out_a_mem_7_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_size),
    .auto_fsa_fbus_xing_out_a_mem_7_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_source),
    .auto_fsa_fbus_xing_out_a_mem_7_address       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_address),
    .auto_fsa_fbus_xing_out_a_mem_7_mask          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_mask),
    .auto_fsa_fbus_xing_out_a_mem_7_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_data),
    .auto_fsa_fbus_xing_out_a_mem_7_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_a_mem_7_corrupt),
    .auto_fsa_fbus_xing_out_a_ridx                (auto_coupler_to_fsa_fsa_fbus_xing_out_a_ridx),
    .auto_fsa_fbus_xing_out_a_widx                (auto_coupler_to_fsa_fsa_fbus_xing_out_a_widx),
    .auto_fsa_fbus_xing_out_a_safe_ridx_valid     (auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_ridx_valid),
    .auto_fsa_fbus_xing_out_a_safe_widx_valid     (auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_widx_valid),
    .auto_fsa_fbus_xing_out_a_safe_source_reset_n (auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_source_reset_n),
    .auto_fsa_fbus_xing_out_a_safe_sink_reset_n   (auto_coupler_to_fsa_fsa_fbus_xing_out_a_safe_sink_reset_n),
    .auto_fsa_fbus_xing_out_d_mem_0_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_opcode),
    .auto_fsa_fbus_xing_out_d_mem_0_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_size),
    .auto_fsa_fbus_xing_out_d_mem_0_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_source),
    .auto_fsa_fbus_xing_out_d_mem_0_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_denied),
    .auto_fsa_fbus_xing_out_d_mem_0_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_data),
    .auto_fsa_fbus_xing_out_d_mem_0_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_0_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_1_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_opcode),
    .auto_fsa_fbus_xing_out_d_mem_1_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_size),
    .auto_fsa_fbus_xing_out_d_mem_1_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_source),
    .auto_fsa_fbus_xing_out_d_mem_1_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_denied),
    .auto_fsa_fbus_xing_out_d_mem_1_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_data),
    .auto_fsa_fbus_xing_out_d_mem_1_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_1_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_2_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_opcode),
    .auto_fsa_fbus_xing_out_d_mem_2_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_size),
    .auto_fsa_fbus_xing_out_d_mem_2_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_source),
    .auto_fsa_fbus_xing_out_d_mem_2_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_denied),
    .auto_fsa_fbus_xing_out_d_mem_2_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_data),
    .auto_fsa_fbus_xing_out_d_mem_2_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_2_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_3_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_opcode),
    .auto_fsa_fbus_xing_out_d_mem_3_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_size),
    .auto_fsa_fbus_xing_out_d_mem_3_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_source),
    .auto_fsa_fbus_xing_out_d_mem_3_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_denied),
    .auto_fsa_fbus_xing_out_d_mem_3_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_data),
    .auto_fsa_fbus_xing_out_d_mem_3_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_3_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_4_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_opcode),
    .auto_fsa_fbus_xing_out_d_mem_4_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_size),
    .auto_fsa_fbus_xing_out_d_mem_4_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_source),
    .auto_fsa_fbus_xing_out_d_mem_4_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_denied),
    .auto_fsa_fbus_xing_out_d_mem_4_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_data),
    .auto_fsa_fbus_xing_out_d_mem_4_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_4_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_5_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_opcode),
    .auto_fsa_fbus_xing_out_d_mem_5_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_size),
    .auto_fsa_fbus_xing_out_d_mem_5_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_source),
    .auto_fsa_fbus_xing_out_d_mem_5_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_denied),
    .auto_fsa_fbus_xing_out_d_mem_5_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_data),
    .auto_fsa_fbus_xing_out_d_mem_5_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_5_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_6_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_opcode),
    .auto_fsa_fbus_xing_out_d_mem_6_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_size),
    .auto_fsa_fbus_xing_out_d_mem_6_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_source),
    .auto_fsa_fbus_xing_out_d_mem_6_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_denied),
    .auto_fsa_fbus_xing_out_d_mem_6_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_data),
    .auto_fsa_fbus_xing_out_d_mem_6_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_6_corrupt),
    .auto_fsa_fbus_xing_out_d_mem_7_opcode        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_opcode),
    .auto_fsa_fbus_xing_out_d_mem_7_size          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_size),
    .auto_fsa_fbus_xing_out_d_mem_7_source        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_source),
    .auto_fsa_fbus_xing_out_d_mem_7_denied        (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_denied),
    .auto_fsa_fbus_xing_out_d_mem_7_data          (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_data),
    .auto_fsa_fbus_xing_out_d_mem_7_corrupt       (auto_coupler_to_fsa_fsa_fbus_xing_out_d_mem_7_corrupt),
    .auto_fsa_fbus_xing_out_d_ridx                (auto_coupler_to_fsa_fsa_fbus_xing_out_d_ridx),
    .auto_fsa_fbus_xing_out_d_widx                (auto_coupler_to_fsa_fsa_fbus_xing_out_d_widx),
    .auto_fsa_fbus_xing_out_d_safe_ridx_valid     (auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_ridx_valid),
    .auto_fsa_fbus_xing_out_d_safe_widx_valid     (auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_widx_valid),
    .auto_fsa_fbus_xing_out_d_safe_source_reset_n (auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_source_reset_n),
    .auto_fsa_fbus_xing_out_d_safe_sink_reset_n   (auto_coupler_to_fsa_fsa_fbus_xing_out_d_safe_sink_reset_n),
    .auto_tl_in_a_ready                           (_coupler_to_fsa_auto_tl_in_a_ready),
    .auto_tl_in_a_valid                           (_fbus_xbar_auto_anon_out_1_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_opcode                     (_fbus_xbar_auto_anon_out_1_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_param                      (_fbus_xbar_auto_anon_out_1_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_size                       (_fbus_xbar_auto_anon_out_1_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_source                     (_fbus_xbar_auto_anon_out_1_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_address                    (_fbus_xbar_auto_anon_out_1_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_mask                       (_fbus_xbar_auto_anon_out_1_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_data                       (_fbus_xbar_auto_anon_out_1_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_a_bits_corrupt                    (_fbus_xbar_auto_anon_out_1_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_d_ready                           (_fbus_xbar_auto_anon_out_1_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:240:32]
    .auto_tl_in_d_valid                           (_coupler_to_fsa_auto_tl_in_d_valid),
    .auto_tl_in_d_bits_opcode                     (_coupler_to_fsa_auto_tl_in_d_bits_opcode),
    .auto_tl_in_d_bits_param                      (_coupler_to_fsa_auto_tl_in_d_bits_param),
    .auto_tl_in_d_bits_size                       (_coupler_to_fsa_auto_tl_in_d_bits_size),
    .auto_tl_in_d_bits_source                     (_coupler_to_fsa_auto_tl_in_d_bits_source),
    .auto_tl_in_d_bits_sink                       (_coupler_to_fsa_auto_tl_in_d_bits_sink),
    .auto_tl_in_d_bits_denied                     (_coupler_to_fsa_auto_tl_in_d_bits_denied),
    .auto_tl_in_d_bits_data                       (_coupler_to_fsa_auto_tl_in_d_bits_data),
    .auto_tl_in_d_bits_corrupt                    (_coupler_to_fsa_auto_tl_in_d_bits_corrupt)
  );	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
endmodule

