// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module InstructionMerger(	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
  input         clock,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
  input         reset,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
  output        io_in_ready,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
  input         io_in_valid,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
  input  [31:0] io_in_bits,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
  input         io_out_ready,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
  output        io_out_valid,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
  output [95:0] io_out_bits,	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
  output        io_inflight	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:12:14]
);

  reg  [31:0] buf_0;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:17:16]
  reg  [31:0] buf_1;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:17:16]
  reg  [31:0] buf_2;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:17:16]
  reg  [1:0]  cnt;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:18:20]
  wire        _io_in_ready_T_2 = io_out_ready & (&cnt);	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:18:20, :29:23, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        io_in_ready_0 = cnt != 2'h3 | _io_in_ready_T_2;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20, :31:{22,28}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [1:0]  w_addr = _io_in_ready_T_2 ? 2'h0 : cnt;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20, :20:19, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire        _cnt_T_2 = io_in_ready_0 & io_in_valid;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:31:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
    if (_cnt_T_2 & w_addr == 2'h0)	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16, :20:19, :22:20, :23:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      buf_0 <= io_in_bits;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:17:16]
    if (_cnt_T_2 & w_addr == 2'h1)	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16, :20:19, :22:20, :23:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      buf_1 <= io_in_bits;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:17:16]
    if (_cnt_T_2 & w_addr == 2'h2)	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16, :20:19, :22:20, :23:17, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      buf_2 <= io_in_bits;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:17:16]
    if (reset)	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
      cnt <= 2'h0;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20]
    else if (_io_in_ready_T_2)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      cnt <= {1'h0, _cnt_T_2};	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:18:20, :24:16, :27:9, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    else if (_cnt_T_2)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      cnt <= cnt + 2'h1;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20, :24:16]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
    initial begin	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
        `INIT_RANDOM_PROLOG_	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
        end	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
        buf_0 = _RANDOM[2'h0];	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16]
        buf_1 = _RANDOM[2'h1];	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16]
        buf_2 = _RANDOM[2'h2];	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16]
        cnt = _RANDOM[2'h3][1:0];	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_in_ready = io_in_ready_0;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :31:28]
  assign io_out_valid = &cnt;	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20, :29:23]
  assign io_out_bits = {buf_2, buf_1, buf_0};	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :17:16, :30:22]
  assign io_inflight = (|cnt) & ~(&cnt);	// @[generators/fsa/src/main/scala/fsa/frontend/Decoder.scala:11:7, :18:20, :29:23, :32:{22,30,33}]
endmodule

