// Generated by CIRCT firtool-1.75.0
module OutputDelayer(	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:41:7]
  input         clock,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:41:7]
  input         io_in_0_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_0_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_0_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_1_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_1_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_1_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_2_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_2_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_2_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_3_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_3_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_3_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_4_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_4_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_4_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_5_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_5_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_5_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_6_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_6_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_6_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_7_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_7_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_7_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_8_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_8_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_8_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_9_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_9_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_9_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_10_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_10_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_10_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_11_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_11_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_11_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_12_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_12_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_12_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_13_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_13_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_13_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_14_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_14_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_14_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input         io_in_15_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [7:0]  io_in_15_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  input  [22:0] io_in_15_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_0_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_0_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_0_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_1_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_1_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_1_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_2_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_2_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_2_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_3_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_3_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_3_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_4_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_4_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_4_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_5_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_5_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_5_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_6_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_6_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_6_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_7_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_7_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_7_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_8_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_8_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_8_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_9_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_9_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_9_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_10_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_10_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_10_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_11_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_11_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_11_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_12_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_12_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_12_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_13_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_13_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_13_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_14_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_14_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_14_mantissa,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output        io_out_15_sign,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [7:0]  io_out_15_exp,	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
  output [22:0] io_out_15_mantissa	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:42:14]
);

  InputDelayer_1 impl (	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:47:20]
    .clock                       (clock),
    .io_in_bits_data_0_sign      (io_in_0_sign),
    .io_in_bits_data_0_exp       (io_in_0_exp),
    .io_in_bits_data_0_mantissa  (io_in_0_mantissa),
    .io_in_bits_data_1_sign      (io_in_1_sign),
    .io_in_bits_data_1_exp       (io_in_1_exp),
    .io_in_bits_data_1_mantissa  (io_in_1_mantissa),
    .io_in_bits_data_2_sign      (io_in_2_sign),
    .io_in_bits_data_2_exp       (io_in_2_exp),
    .io_in_bits_data_2_mantissa  (io_in_2_mantissa),
    .io_in_bits_data_3_sign      (io_in_3_sign),
    .io_in_bits_data_3_exp       (io_in_3_exp),
    .io_in_bits_data_3_mantissa  (io_in_3_mantissa),
    .io_in_bits_data_4_sign      (io_in_4_sign),
    .io_in_bits_data_4_exp       (io_in_4_exp),
    .io_in_bits_data_4_mantissa  (io_in_4_mantissa),
    .io_in_bits_data_5_sign      (io_in_5_sign),
    .io_in_bits_data_5_exp       (io_in_5_exp),
    .io_in_bits_data_5_mantissa  (io_in_5_mantissa),
    .io_in_bits_data_6_sign      (io_in_6_sign),
    .io_in_bits_data_6_exp       (io_in_6_exp),
    .io_in_bits_data_6_mantissa  (io_in_6_mantissa),
    .io_in_bits_data_7_sign      (io_in_7_sign),
    .io_in_bits_data_7_exp       (io_in_7_exp),
    .io_in_bits_data_7_mantissa  (io_in_7_mantissa),
    .io_in_bits_data_8_sign      (io_in_8_sign),
    .io_in_bits_data_8_exp       (io_in_8_exp),
    .io_in_bits_data_8_mantissa  (io_in_8_mantissa),
    .io_in_bits_data_9_sign      (io_in_9_sign),
    .io_in_bits_data_9_exp       (io_in_9_exp),
    .io_in_bits_data_9_mantissa  (io_in_9_mantissa),
    .io_in_bits_data_10_sign     (io_in_10_sign),
    .io_in_bits_data_10_exp      (io_in_10_exp),
    .io_in_bits_data_10_mantissa (io_in_10_mantissa),
    .io_in_bits_data_11_sign     (io_in_11_sign),
    .io_in_bits_data_11_exp      (io_in_11_exp),
    .io_in_bits_data_11_mantissa (io_in_11_mantissa),
    .io_in_bits_data_12_sign     (io_in_12_sign),
    .io_in_bits_data_12_exp      (io_in_12_exp),
    .io_in_bits_data_12_mantissa (io_in_12_mantissa),
    .io_in_bits_data_13_sign     (io_in_13_sign),
    .io_in_bits_data_13_exp      (io_in_13_exp),
    .io_in_bits_data_13_mantissa (io_in_13_mantissa),
    .io_in_bits_data_14_sign     (io_in_14_sign),
    .io_in_bits_data_14_exp      (io_in_14_exp),
    .io_in_bits_data_14_mantissa (io_in_14_mantissa),
    .io_in_bits_data_15_sign     (io_in_15_sign),
    .io_in_bits_data_15_exp      (io_in_15_exp),
    .io_in_bits_data_15_mantissa (io_in_15_mantissa),
    .io_out_0_sign               (io_out_0_sign),
    .io_out_0_exp                (io_out_0_exp),
    .io_out_0_mantissa           (io_out_0_mantissa),
    .io_out_1_sign               (io_out_1_sign),
    .io_out_1_exp                (io_out_1_exp),
    .io_out_1_mantissa           (io_out_1_mantissa),
    .io_out_2_sign               (io_out_2_sign),
    .io_out_2_exp                (io_out_2_exp),
    .io_out_2_mantissa           (io_out_2_mantissa),
    .io_out_3_sign               (io_out_3_sign),
    .io_out_3_exp                (io_out_3_exp),
    .io_out_3_mantissa           (io_out_3_mantissa),
    .io_out_4_sign               (io_out_4_sign),
    .io_out_4_exp                (io_out_4_exp),
    .io_out_4_mantissa           (io_out_4_mantissa),
    .io_out_5_sign               (io_out_5_sign),
    .io_out_5_exp                (io_out_5_exp),
    .io_out_5_mantissa           (io_out_5_mantissa),
    .io_out_6_sign               (io_out_6_sign),
    .io_out_6_exp                (io_out_6_exp),
    .io_out_6_mantissa           (io_out_6_mantissa),
    .io_out_7_sign               (io_out_7_sign),
    .io_out_7_exp                (io_out_7_exp),
    .io_out_7_mantissa           (io_out_7_mantissa),
    .io_out_8_sign               (io_out_8_sign),
    .io_out_8_exp                (io_out_8_exp),
    .io_out_8_mantissa           (io_out_8_mantissa),
    .io_out_9_sign               (io_out_9_sign),
    .io_out_9_exp                (io_out_9_exp),
    .io_out_9_mantissa           (io_out_9_mantissa),
    .io_out_10_sign              (io_out_10_sign),
    .io_out_10_exp               (io_out_10_exp),
    .io_out_10_mantissa          (io_out_10_mantissa),
    .io_out_11_sign              (io_out_11_sign),
    .io_out_11_exp               (io_out_11_exp),
    .io_out_11_mantissa          (io_out_11_mantissa),
    .io_out_12_sign              (io_out_12_sign),
    .io_out_12_exp               (io_out_12_exp),
    .io_out_12_mantissa          (io_out_12_mantissa),
    .io_out_13_sign              (io_out_13_sign),
    .io_out_13_exp               (io_out_13_exp),
    .io_out_13_mantissa          (io_out_13_mantissa),
    .io_out_14_sign              (io_out_14_sign),
    .io_out_14_exp               (io_out_14_exp),
    .io_out_14_mantissa          (io_out_14_mantissa),
    .io_out_15_sign              (io_out_15_sign),
    .io_out_15_exp               (io_out_15_exp),
    .io_out_15_mantissa          (io_out_15_mantissa)
  );	// @[generators/fsa/src/main/scala/fsa/InputDelayer.scala:47:20]
endmodule

