// Generated by CIRCT firtool-1.75.0
module RawFloat_MulAddExp2_1(	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:66:7]
  input         io_in_exp2,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_a_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_a_isInf,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_a_isNaN,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_a_sign,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input  [8:0]  io_in_a_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input  [23:0] io_in_a_mantissa,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_b_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_b_isInf,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_b_isNaN,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_b_sign,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input  [8:0]  io_in_b_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input  [23:0] io_in_b_mantissa,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_c_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_c_isInf,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_c_isNaN,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input         io_in_c_sign,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input  [8:0]  io_in_c_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  input  [23:0] io_in_c_mantissa,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  output        io_out_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  output        io_out_isInf,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  output        io_out_isNaN,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  output        io_out_sign,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  output [10:0] io_out_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
  output [25:0] io_out_mantissa	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:79:14]
);

  wire [8:0]       _split_io_outInt;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire [2:0]       _split_io_outFracMSBs;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire             _split_io_outRawFloat_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire             _split_io_outRawFloat_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire             _split_io_outRawFloat_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire             _split_io_outRawFloat_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire [8:0]       _split_io_outRawFloat_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire [23:0]      _split_io_outRawFloat_mantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  wire             _fma_io_out_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:73:19]
  wire             _fma_io_out_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:73:19]
  wire             _fma_io_out_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:73:19]
  wire [10:0]      _fma_io_out_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:73:19]
  wire [7:0][31:0] _GEN = '{32'h3F5CAE0F, 32'h3F640507, 32'h3F6AE156, 32'h3F711D65, 32'h3F768DCF, 32'h3F7B00A2, 32'h3F7E3C91, 32'h3F800000};
  wire [7:0][31:0] _GEN_0 = '{32'h3EB95C1E, 32'h3ECA22E7, 32'h3EDC6E66, 32'h3EF061C9, 32'h3F0311B7, 32'h3F0EEE96, 32'h3F1BDE51, 32'h3F29F9C9};
  wire [31:0]      _GEN_1 = _GEN_0[_split_io_outFracMSBs];	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:27]
  wire [31:0]      _GEN_2 = _GEN[_split_io_outFracMSBs];	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:27]
  RawFloat_FMA fma (	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:73:19]
    .io_a_isZero     (io_in_exp2 ? _split_io_outRawFloat_isZero : io_in_a_isZero),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, :99:12, :104:20, :105:14]
    .io_a_isInf      (io_in_exp2 ? _split_io_outRawFloat_isInf : io_in_a_isInf),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, :99:12, :104:20, :105:14]
    .io_a_isNaN      (io_in_exp2 ? _split_io_outRawFloat_isNaN : io_in_a_isNaN),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, :99:12, :104:20, :105:14]
    .io_a_sign       (io_in_exp2 ? _split_io_outRawFloat_sign : io_in_a_sign),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, :99:12, :104:20, :105:14]
    .io_a_exp        (io_in_exp2 ? _split_io_outRawFloat_exp : io_in_a_exp),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, :99:12, :104:20, :105:14]
    .io_a_mantissa   (io_in_exp2 ? _split_io_outRawFloat_mantissa : io_in_a_mantissa),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13, :99:12, :104:20, :105:14]
    .io_b_isZero     (io_in_exp2 ? _GEN_1[30:23] == 8'h0 : io_in_b_isZero),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:100:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:{12,25}]
    .io_b_isInf      (io_in_exp2 ? (&(_GEN_1[30:23])) & ~(|(_GEN_1[22:0])) : io_in_b_isInf),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:100:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{11,24,29,32,51}]
    .io_b_isNaN      (io_in_exp2 ? (&(_GEN_1[30:23])) & (|(_GEN_1[22:0])) : io_in_b_isNaN),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:100:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,51}, :26:{11,29}]
    .io_b_sign       (io_in_exp2 ? _GEN_1[31] : io_in_b_sign),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:100:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:27, :28:{10,19}]
    .io_b_exp        (io_in_exp2 ? {1'h0, _GEN_1[30:23]} - 9'h7F : io_in_b_exp),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:100:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:{9,27}]
    .io_b_mantissa   (io_in_exp2 ? {1'h1, _GEN_1[22:0]} : io_in_b_mantissa),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:100:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:27, :22:35, :34:{16,28}]
    .io_c_isZero     (io_in_exp2 ? _GEN_2[30:23] == 8'h0 : io_in_c_isZero),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:101:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:{12,25}]
    .io_c_isInf      (io_in_exp2 ? (&(_GEN_2[30:23])) & ~(|(_GEN_2[22:0])) : io_in_c_isInf),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:101:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{11,24,29,32,51}]
    .io_c_isNaN      (io_in_exp2 ? (&(_GEN_2[30:23])) & (|(_GEN_2[22:0])) : io_in_c_isNaN),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:101:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,51}, :26:{11,29}]
    .io_c_sign       (io_in_exp2 ? _GEN_2[31] : io_in_c_sign),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:101:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:27, :28:{10,19}]
    .io_c_exp        (io_in_exp2 ? {1'h0, _GEN_2[30:23]} - 9'h7F : io_in_c_exp),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:101:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:{9,27}]
    .io_c_mantissa   (io_in_exp2 ? {1'h1, _GEN_2[22:0]} : io_in_c_mantissa),	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:101:12, :118:24, generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:27, :22:35, :34:{16,28}]
    .io_out_isZero   (_fma_io_out_isZero),
    .io_out_isInf    (_fma_io_out_isInf),
    .io_out_isNaN    (io_out_isNaN),
    .io_out_sign     (_fma_io_out_sign),
    .io_out_exp      (_fma_io_out_exp),
    .io_out_mantissa (io_out_mantissa)
  );	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:73:19]
  RawFloat_SplitIF_1 split (	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
    .io_in_isZero            (io_in_a_isZero),
    .io_in_isInf             (io_in_a_isInf),
    .io_in_isNaN             (io_in_a_isNaN),
    .io_in_sign              (io_in_a_sign),
    .io_in_exp               (io_in_a_exp),
    .io_in_mantissa          (io_in_a_mantissa),
    .io_outInt               (_split_io_outInt),
    .io_outFracMSBs          (_split_io_outFracMSBs),
    .io_outRawFloat_isZero   (_split_io_outRawFloat_isZero),
    .io_outRawFloat_isInf    (_split_io_outRawFloat_isInf),
    .io_outRawFloat_isNaN    (_split_io_outRawFloat_isNaN),
    .io_outRawFloat_sign     (_split_io_outRawFloat_sign),
    .io_outRawFloat_exp      (_split_io_outRawFloat_exp),
    .io_outRawFloat_mantissa (_split_io_outRawFloat_mantissa)
  );	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:93:13]
  assign io_out_isZero = io_in_exp2 ? _fma_io_out_isInf : _fma_io_out_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:66:7, :73:19, :102:10, :104:20, :108:19]
  assign io_out_isInf = ~io_in_exp2 & _fma_io_out_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:66:7, :73:19, :102:10, :104:20, :106:17, :107:18]
  assign io_out_sign = ~io_in_exp2 & _fma_io_out_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:66:7, :73:19, :102:10, :104:20, :106:17]
  assign io_out_exp = io_in_exp2 ? {{2{_split_io_outInt[8]}}, _split_io_outInt} + _fma_io_out_exp : _fma_io_out_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/Exp2.scala:66:7, :73:19, :93:13, :102:10, :104:20, :109:{16,35}]
endmodule

