// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Reciprocal(	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
  input         clock,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
  input         reset,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
  input  [31:0] io_in,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  input         io_in_valid,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_out_valid,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawA_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawA_isInf,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawA_isNaN,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawA_sign,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output [8:0]  io_fma_rawA_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output [23:0] io_fma_rawA_mantissa,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawB_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawB_isInf,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawB_isNaN,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawB_sign,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output [8:0]  io_fma_rawB_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output [23:0] io_fma_rawB_mantissa,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output        io_fma_rawC_isZero,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output [8:0]  io_fma_rawC_exp,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  output [23:0] io_fma_rawC_mantissa,	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
  input  [31:0] io_fma_rounded_result	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:24:14]
);

  wire        xe_isInf = io_in[30:23] == 8'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:25]
  wire        xm_isInf = (&(io_in[30:23])) & ~(|(io_in[22:0]));	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,29,32,51}]
  reg  [4:0]  cnt;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20]
  wire        done = cnt == 5'h12;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20, :54:18]
  reg         reg_r_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
  reg         reg_r_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
  reg         reg_r_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
  reg         reg_r_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
  reg  [8:0]  reg_r_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
  reg  [23:0] reg_r_mantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
  reg         reg_p_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
  reg         reg_p_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
  reg         reg_p_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
  reg         reg_p_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
  reg  [8:0]  reg_p_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
  reg  [23:0] reg_p_mantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
  wire        _GEN = done | cnt[0];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20, :54:18, :89:13, :99:14, :101:17, :102:22, :104:17, :107:17]
  wire        _GEN_0 = io_in_valid & cnt[0];	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:12, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20, :83:23, :88:27, :89:{13,18}]
  always @(posedge clock) begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
    if (reset) begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
      cnt <= 5'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20]
      reg_r_isZero <= 1'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      reg_r_isInf <= 1'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      reg_r_isNaN <= 1'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      reg_r_sign <= 1'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      reg_r_exp <= 9'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      reg_r_mantissa <= 24'h800000;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
    end
    else begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
      if (io_in_valid & cnt != 5'h12)	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20, :54:18, :56:{20,23}]
        cnt <= cnt + 5'h1;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20, :57:16]
      else if (done)	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:54:18]
        cnt <= 5'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20]
      reg_r_isZero <= ~done & (_GEN_0 ? io_fma_rounded_result[30:23] == 8'h0 : reg_r_isZero);	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:{12,25}, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:54:18, :83:23, :86:14, :87:11, :88:27, :89:18]
      reg_r_isInf <= ~done & (_GEN_0 ? (&(io_fma_rounded_result[30:23])) & ~(|(io_fma_rounded_result[22:0])) : reg_r_isInf);	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :24:12, :25:{11,24,29,32,51}, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:54:18, :83:23, :86:14, :87:11, :88:27, :89:18]
      reg_r_isNaN <= ~done & (_GEN_0 ? (&(io_fma_rounded_result[30:23])) & (|(io_fma_rounded_result[22:0])) : reg_r_isNaN);	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :24:12, :25:{24,51}, :26:{11,29}, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:54:18, :83:23, :86:14, :87:11, :88:27, :89:18]
      reg_r_sign <= ~done & (_GEN_0 ? io_fma_rounded_result[31] : reg_r_sign);	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:12, :28:{10,19}, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:54:18, :83:23, :86:14, :87:11, :88:27, :89:18]
      if (done) begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:54:18]
        reg_r_exp <= 9'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
        reg_r_mantissa <= 24'h800000;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      end
      else if (_GEN_0) begin	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:12, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23, :88:27, :89:18]
        reg_r_exp <= {1'h0, io_fma_rounded_result[30:23]} - 9'h7F;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:27, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
        reg_r_mantissa <= {1'h1, io_fma_rounded_result[22:0]};	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:22:35, :34:28, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:83:23]
      end
    end
    if (done | ~io_in_valid | cnt[0]) begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:53:20, :54:18, :84:18, :86:14, :88:27, :89:{13,18}]
    end
    else begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18, :86:14, :88:27, :89:18]
      reg_p_isZero <= io_fma_rounded_result[30:23] == 8'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :24:25, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
      reg_p_isInf <= (&(io_fma_rounded_result[30:23])) & ~(|(io_fma_rounded_result[22:0]));	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,29,32,51}, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
      reg_p_isNaN <= (&(io_fma_rounded_result[30:23])) & (|(io_fma_rounded_result[22:0]));	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,51}, :26:29, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
      reg_p_sign <= io_fma_rounded_result[31];	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:19, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
      reg_p_exp <= {1'h0, io_fma_rounded_result[30:23]} - 9'h7F;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:27, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
      reg_p_mantissa <= {1'h1, io_fma_rounded_result[22:0]};	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:22:35, :34:28, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:84:18]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
    initial begin	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
        `INIT_RANDOM_PROLOG_	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
        end	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
        cnt = _RANDOM[2'h0][4:0];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20]
        reg_r_isZero = _RANDOM[2'h0][5];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :83:23]
        reg_r_isInf = _RANDOM[2'h0][6];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :83:23]
        reg_r_isNaN = _RANDOM[2'h0][7];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :83:23]
        reg_r_sign = _RANDOM[2'h0][8];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :83:23]
        reg_r_exp = _RANDOM[2'h0][17:9];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :83:23]
        reg_r_mantissa = {_RANDOM[2'h0][31:18], _RANDOM[2'h1][9:0]};	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :83:23]
        reg_p_isZero = _RANDOM[2'h1][10];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23, :84:18]
        reg_p_isInf = _RANDOM[2'h1][11];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23, :84:18]
        reg_p_isNaN = _RANDOM[2'h1][12];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23, :84:18]
        reg_p_sign = _RANDOM[2'h1][13];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23, :84:18]
        reg_p_exp = _RANDOM[2'h1][22:14];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23, :84:18]
        reg_p_mantissa = {_RANDOM[2'h1][31:23], _RANDOM[2'h2][14:0]};	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23, :84:18]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = done;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :54:18]
  assign io_fma_rawA_isZero = reg_r_isZero;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23]
  assign io_fma_rawA_isInf = reg_r_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23]
  assign io_fma_rawA_isNaN = reg_r_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23]
  assign io_fma_rawA_sign = reg_r_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23]
  assign io_fma_rawA_exp = reg_r_exp;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23]
  assign io_fma_rawA_mantissa = reg_r_mantissa;	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :83:23]
  assign io_fma_rawB_isZero = done ? xm_isInf : cnt[0] ? reg_p_isZero : xe_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:25, :25:29, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :54:18, :84:18, :89:13, :99:14, :100:17, :102:22, :103:17, :106:17]
  assign io_fma_rawB_isInf = done ? xe_isInf : cnt[0] ? reg_p_isInf : xm_isInf;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:24:25, :25:29, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :54:18, :84:18, :89:13, :99:14, :100:17, :102:22, :103:17, :106:17]
  assign io_fma_rawB_isNaN = done | ~(cnt[0]) ? (&(io_in[30:23])) & (|(io_in[22:0])) : reg_p_isNaN;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :22:35, :25:{24,51}, :26:29, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :54:18, :84:18, :89:13, :99:14, :100:17, :102:22]
  assign io_fma_rawB_sign = done ? io_in[31] : ~(cnt[0]) | reg_p_sign;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:28:19, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :54:18, :84:18, :89:13, :99:14, :100:17, :102:22, :103:17, :106:17]
  assign io_fma_rawB_exp = done ? 9'h0 - ({1'h0, io_in[30:23]} - 9'h7F) : cnt[0] ? reg_p_exp : 9'h0;	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:21:{27,35}, :29:27, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :44:10, :46:13, :53:20, :54:18, :84:18, :89:13, :99:14, :100:17, :102:22, :103:17, :106:17]
  assign io_fma_rawB_mantissa = done ? 24'h800000 : cnt[0] ? reg_p_mantissa : {1'h1, io_in[22:0]};	// @[generators/easyfloat/src/main/scala/easyfloat/RawFloat.scala:22:35, :34:28, generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :54:18, :84:18, :89:13, :99:14, :100:17, :102:22, :103:17, :106:17]
  assign io_fma_rawC_isZero = done | cnt[0];	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :53:20, :54:18, :89:13, :99:14, :101:17, :102:22]
  assign io_fma_rawC_exp = {8'h0, ~_GEN};	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :99:14, :101:17, :102:22, :104:17, :107:17]
  assign io_fma_rawC_mantissa = {~_GEN, 23'h0};	// @[generators/easyfloat/src/main/scala/easyfloat/Reciprocal.scala:22:7, :99:14, :101:17, :102:22, :104:17, :107:17]
endmodule

