// Generated by CIRCT firtool-1.75.0
module ShiftRightJam_16(	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:12:7]
  input  [52:0] io_in,	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:14:14]
  input  [10:0] io_shamt,	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:14:14]
  output [52:0] io_out,	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:14:14]
  output        io_sticky	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:14:14]
);

  wire        exceed_max_shift = io_shamt > 11'h35;	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:20:35]
  wire [63:0] _sticky_mask_T = 64'h1 << io_shamt[5:0];	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:21:23, :23:11]
  assign io_out = exceed_max_shift ? 53'h0 : io_in >> io_shamt;	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:12:7, :20:35, :24:{16,46}]
  assign io_sticky = |(io_in & (_sticky_mask_T[52:0] - 53'h1 | {53{exceed_max_shift}}));	// @[generators/easyfloat/src/main/scala/easyfloat/Utils.scala:12:7, :20:35, :23:{11,28,47,53}, :25:{23,38}]
endmodule

