// Generated by CIRCT firtool-1.75.0
module TLAsyncCrossingSource_a16d32s4k1z3u(	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [15:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_0_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_0_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_0_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_0_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_0_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_0_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_0_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_0_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_1_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_1_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_1_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_1_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_1_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_1_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_1_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_1_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_2_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_2_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_2_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_2_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_2_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_2_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_2_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_2_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_3_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_3_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_3_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_3_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_3_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_3_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_3_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_3_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_4_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_4_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_4_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_4_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_4_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_4_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_4_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_4_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_5_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_5_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_5_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_5_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_5_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_5_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_5_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_5_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_6_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_6_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_6_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_6_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_6_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_6_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_6_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_6_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_7_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_7_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_mem_7_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_7_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_a_mem_7_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_mem_7_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_mem_7_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_mem_7_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_a_ridx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_widx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_a_safe_ridx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_safe_widx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_safe_source_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_a_safe_sink_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_0_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_0_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_0_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_0_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_0_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_0_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_1_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_1_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_1_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_1_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_1_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_1_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_2_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_2_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_2_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_2_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_2_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_2_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_3_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_3_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_3_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_3_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_3_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_3_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_4_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_4_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_4_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_4_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_4_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_4_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_5_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_5_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_5_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_5_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_5_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_5_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_6_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_6_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_6_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_6_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_6_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_6_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_7_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_mem_7_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_mem_7_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_7_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_d_mem_7_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_mem_7_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_d_ridx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_widx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_d_safe_ridx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_safe_widx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_safe_source_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_d_safe_sink_reset_n	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire       _nodeIn_d_sink_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire [2:0] _nodeIn_d_sink_io_deq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire [1:0] _nodeIn_d_sink_io_deq_bits_param;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire [2:0] _nodeIn_d_sink_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire [3:0] _nodeIn_d_sink_io_deq_bits_source;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire       _nodeIn_d_sink_io_deq_bits_sink;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire       _nodeIn_d_sink_io_deq_bits_denied;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire       _nodeIn_d_sink_io_deq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  wire       _nodeOut_a_source_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:220:24]
  TLMonitor_4 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_nodeOut_a_source_io_enq_ready),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:220:24]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (_nodeIn_d_sink_io_deq_valid),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_opcode  (_nodeIn_d_sink_io_deq_bits_opcode),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_param   (_nodeIn_d_sink_io_deq_bits_param),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_size    (_nodeIn_d_sink_io_deq_bits_size),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_source  (_nodeIn_d_sink_io_deq_bits_source),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_sink    (_nodeIn_d_sink_io_deq_bits_sink),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_denied  (_nodeIn_d_sink_io_deq_bits_denied),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .io_in_d_bits_corrupt (_nodeIn_d_sink_io_deq_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  AsyncQueueSource_TLBundleA_a16d32s4k1z3u nodeOut_a_source (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:220:24]
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_ready                 (_nodeOut_a_source_io_enq_ready),
    .io_enq_valid                 (auto_in_a_valid),
    .io_enq_bits_opcode           (auto_in_a_bits_opcode),
    .io_enq_bits_param            (auto_in_a_bits_param),
    .io_enq_bits_size             (auto_in_a_bits_size),
    .io_enq_bits_source           (auto_in_a_bits_source),
    .io_enq_bits_address          (auto_in_a_bits_address),
    .io_enq_bits_mask             (auto_in_a_bits_mask),
    .io_enq_bits_data             (auto_in_a_bits_data),
    .io_enq_bits_corrupt          (auto_in_a_bits_corrupt),
    .io_async_mem_0_opcode        (auto_out_a_mem_0_opcode),
    .io_async_mem_0_param         (auto_out_a_mem_0_param),
    .io_async_mem_0_size          (auto_out_a_mem_0_size),
    .io_async_mem_0_source        (auto_out_a_mem_0_source),
    .io_async_mem_0_address       (auto_out_a_mem_0_address),
    .io_async_mem_0_mask          (auto_out_a_mem_0_mask),
    .io_async_mem_0_data          (auto_out_a_mem_0_data),
    .io_async_mem_0_corrupt       (auto_out_a_mem_0_corrupt),
    .io_async_mem_1_opcode        (auto_out_a_mem_1_opcode),
    .io_async_mem_1_param         (auto_out_a_mem_1_param),
    .io_async_mem_1_size          (auto_out_a_mem_1_size),
    .io_async_mem_1_source        (auto_out_a_mem_1_source),
    .io_async_mem_1_address       (auto_out_a_mem_1_address),
    .io_async_mem_1_mask          (auto_out_a_mem_1_mask),
    .io_async_mem_1_data          (auto_out_a_mem_1_data),
    .io_async_mem_1_corrupt       (auto_out_a_mem_1_corrupt),
    .io_async_mem_2_opcode        (auto_out_a_mem_2_opcode),
    .io_async_mem_2_param         (auto_out_a_mem_2_param),
    .io_async_mem_2_size          (auto_out_a_mem_2_size),
    .io_async_mem_2_source        (auto_out_a_mem_2_source),
    .io_async_mem_2_address       (auto_out_a_mem_2_address),
    .io_async_mem_2_mask          (auto_out_a_mem_2_mask),
    .io_async_mem_2_data          (auto_out_a_mem_2_data),
    .io_async_mem_2_corrupt       (auto_out_a_mem_2_corrupt),
    .io_async_mem_3_opcode        (auto_out_a_mem_3_opcode),
    .io_async_mem_3_param         (auto_out_a_mem_3_param),
    .io_async_mem_3_size          (auto_out_a_mem_3_size),
    .io_async_mem_3_source        (auto_out_a_mem_3_source),
    .io_async_mem_3_address       (auto_out_a_mem_3_address),
    .io_async_mem_3_mask          (auto_out_a_mem_3_mask),
    .io_async_mem_3_data          (auto_out_a_mem_3_data),
    .io_async_mem_3_corrupt       (auto_out_a_mem_3_corrupt),
    .io_async_mem_4_opcode        (auto_out_a_mem_4_opcode),
    .io_async_mem_4_param         (auto_out_a_mem_4_param),
    .io_async_mem_4_size          (auto_out_a_mem_4_size),
    .io_async_mem_4_source        (auto_out_a_mem_4_source),
    .io_async_mem_4_address       (auto_out_a_mem_4_address),
    .io_async_mem_4_mask          (auto_out_a_mem_4_mask),
    .io_async_mem_4_data          (auto_out_a_mem_4_data),
    .io_async_mem_4_corrupt       (auto_out_a_mem_4_corrupt),
    .io_async_mem_5_opcode        (auto_out_a_mem_5_opcode),
    .io_async_mem_5_param         (auto_out_a_mem_5_param),
    .io_async_mem_5_size          (auto_out_a_mem_5_size),
    .io_async_mem_5_source        (auto_out_a_mem_5_source),
    .io_async_mem_5_address       (auto_out_a_mem_5_address),
    .io_async_mem_5_mask          (auto_out_a_mem_5_mask),
    .io_async_mem_5_data          (auto_out_a_mem_5_data),
    .io_async_mem_5_corrupt       (auto_out_a_mem_5_corrupt),
    .io_async_mem_6_opcode        (auto_out_a_mem_6_opcode),
    .io_async_mem_6_param         (auto_out_a_mem_6_param),
    .io_async_mem_6_size          (auto_out_a_mem_6_size),
    .io_async_mem_6_source        (auto_out_a_mem_6_source),
    .io_async_mem_6_address       (auto_out_a_mem_6_address),
    .io_async_mem_6_mask          (auto_out_a_mem_6_mask),
    .io_async_mem_6_data          (auto_out_a_mem_6_data),
    .io_async_mem_6_corrupt       (auto_out_a_mem_6_corrupt),
    .io_async_mem_7_opcode        (auto_out_a_mem_7_opcode),
    .io_async_mem_7_param         (auto_out_a_mem_7_param),
    .io_async_mem_7_size          (auto_out_a_mem_7_size),
    .io_async_mem_7_source        (auto_out_a_mem_7_source),
    .io_async_mem_7_address       (auto_out_a_mem_7_address),
    .io_async_mem_7_mask          (auto_out_a_mem_7_mask),
    .io_async_mem_7_data          (auto_out_a_mem_7_data),
    .io_async_mem_7_corrupt       (auto_out_a_mem_7_corrupt),
    .io_async_ridx                (auto_out_a_ridx),
    .io_async_widx                (auto_out_a_widx),
    .io_async_safe_ridx_valid     (auto_out_a_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_out_a_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_out_a_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_out_a_safe_sink_reset_n)
  );	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:220:24]
  AsyncQueueSink_TLBundleD_a16d32s4k1z3u nodeIn_d_sink (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
    .clock                        (clock),
    .reset                        (reset),
    .io_deq_ready                 (auto_in_d_ready),
    .io_deq_valid                 (_nodeIn_d_sink_io_deq_valid),
    .io_deq_bits_opcode           (_nodeIn_d_sink_io_deq_bits_opcode),
    .io_deq_bits_param            (_nodeIn_d_sink_io_deq_bits_param),
    .io_deq_bits_size             (_nodeIn_d_sink_io_deq_bits_size),
    .io_deq_bits_source           (_nodeIn_d_sink_io_deq_bits_source),
    .io_deq_bits_sink             (_nodeIn_d_sink_io_deq_bits_sink),
    .io_deq_bits_denied           (_nodeIn_d_sink_io_deq_bits_denied),
    .io_deq_bits_data             (auto_in_d_bits_data),
    .io_deq_bits_corrupt          (_nodeIn_d_sink_io_deq_bits_corrupt),
    .io_async_mem_0_opcode        (auto_out_d_mem_0_opcode),
    .io_async_mem_0_size          (auto_out_d_mem_0_size),
    .io_async_mem_0_source        (auto_out_d_mem_0_source),
    .io_async_mem_0_denied        (auto_out_d_mem_0_denied),
    .io_async_mem_0_data          (auto_out_d_mem_0_data),
    .io_async_mem_0_corrupt       (auto_out_d_mem_0_corrupt),
    .io_async_mem_1_opcode        (auto_out_d_mem_1_opcode),
    .io_async_mem_1_size          (auto_out_d_mem_1_size),
    .io_async_mem_1_source        (auto_out_d_mem_1_source),
    .io_async_mem_1_denied        (auto_out_d_mem_1_denied),
    .io_async_mem_1_data          (auto_out_d_mem_1_data),
    .io_async_mem_1_corrupt       (auto_out_d_mem_1_corrupt),
    .io_async_mem_2_opcode        (auto_out_d_mem_2_opcode),
    .io_async_mem_2_size          (auto_out_d_mem_2_size),
    .io_async_mem_2_source        (auto_out_d_mem_2_source),
    .io_async_mem_2_denied        (auto_out_d_mem_2_denied),
    .io_async_mem_2_data          (auto_out_d_mem_2_data),
    .io_async_mem_2_corrupt       (auto_out_d_mem_2_corrupt),
    .io_async_mem_3_opcode        (auto_out_d_mem_3_opcode),
    .io_async_mem_3_size          (auto_out_d_mem_3_size),
    .io_async_mem_3_source        (auto_out_d_mem_3_source),
    .io_async_mem_3_denied        (auto_out_d_mem_3_denied),
    .io_async_mem_3_data          (auto_out_d_mem_3_data),
    .io_async_mem_3_corrupt       (auto_out_d_mem_3_corrupt),
    .io_async_mem_4_opcode        (auto_out_d_mem_4_opcode),
    .io_async_mem_4_size          (auto_out_d_mem_4_size),
    .io_async_mem_4_source        (auto_out_d_mem_4_source),
    .io_async_mem_4_denied        (auto_out_d_mem_4_denied),
    .io_async_mem_4_data          (auto_out_d_mem_4_data),
    .io_async_mem_4_corrupt       (auto_out_d_mem_4_corrupt),
    .io_async_mem_5_opcode        (auto_out_d_mem_5_opcode),
    .io_async_mem_5_size          (auto_out_d_mem_5_size),
    .io_async_mem_5_source        (auto_out_d_mem_5_source),
    .io_async_mem_5_denied        (auto_out_d_mem_5_denied),
    .io_async_mem_5_data          (auto_out_d_mem_5_data),
    .io_async_mem_5_corrupt       (auto_out_d_mem_5_corrupt),
    .io_async_mem_6_opcode        (auto_out_d_mem_6_opcode),
    .io_async_mem_6_size          (auto_out_d_mem_6_size),
    .io_async_mem_6_source        (auto_out_d_mem_6_source),
    .io_async_mem_6_denied        (auto_out_d_mem_6_denied),
    .io_async_mem_6_data          (auto_out_d_mem_6_data),
    .io_async_mem_6_corrupt       (auto_out_d_mem_6_corrupt),
    .io_async_mem_7_opcode        (auto_out_d_mem_7_opcode),
    .io_async_mem_7_size          (auto_out_d_mem_7_size),
    .io_async_mem_7_source        (auto_out_d_mem_7_source),
    .io_async_mem_7_denied        (auto_out_d_mem_7_denied),
    .io_async_mem_7_data          (auto_out_d_mem_7_data),
    .io_async_mem_7_corrupt       (auto_out_d_mem_7_corrupt),
    .io_async_ridx                (auto_out_d_ridx),
    .io_async_widx                (auto_out_d_widx),
    .io_async_safe_ridx_valid     (auto_out_d_safe_ridx_valid),
    .io_async_safe_widx_valid     (auto_out_d_safe_widx_valid),
    .io_async_safe_source_reset_n (auto_out_d_safe_source_reset_n),
    .io_async_safe_sink_reset_n   (auto_out_d_safe_sink_reset_n)
  );	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_a_ready = _nodeOut_a_source_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:220:24]
  assign auto_in_d_valid = _nodeIn_d_sink_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_opcode = _nodeIn_d_sink_io_deq_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_param = _nodeIn_d_sink_io_deq_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_size = _nodeIn_d_sink_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_source = _nodeIn_d_sink_io_deq_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_sink = _nodeIn_d_sink_io_deq_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_denied = _nodeIn_d_sink_io_deq_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
  assign auto_in_d_bits_corrupt = _nodeIn_d_sink_io_deq_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:23:9, generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:211:22]
endmodule

