// Generated by CIRCT firtool-1.75.0
module TLInterconnectCoupler_fbus_to_fsa(	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  input         reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:135:7]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_0_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_0_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_0_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_0_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_0_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_0_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_0_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_0_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_1_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_1_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_1_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_1_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_1_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_1_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_1_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_1_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_2_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_2_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_2_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_2_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_2_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_2_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_2_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_2_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_3_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_3_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_3_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_3_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_3_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_3_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_3_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_3_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_4_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_4_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_4_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_4_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_4_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_4_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_4_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_4_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_5_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_5_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_5_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_5_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_5_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_5_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_5_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_5_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_6_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_6_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_6_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_6_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_6_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_6_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_6_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_6_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_7_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_7_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_fsa_fbus_xing_out_a_mem_7_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_7_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_fsa_fbus_xing_out_a_mem_7_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_mem_7_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_fsa_fbus_xing_out_a_mem_7_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_mem_7_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_a_ridx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_a_widx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_a_safe_ridx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_safe_widx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_a_safe_source_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_a_safe_sink_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_0_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_0_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_0_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_0_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_0_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_0_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_1_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_1_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_1_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_1_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_1_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_1_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_2_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_2_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_2_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_2_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_2_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_2_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_3_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_3_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_3_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_3_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_3_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_3_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_4_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_4_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_4_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_4_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_4_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_4_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_5_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_5_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_5_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_5_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_5_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_5_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_6_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_6_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_6_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_6_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_6_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_6_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_7_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_fsa_fbus_xing_out_d_mem_7_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_mem_7_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_7_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_fsa_fbus_xing_out_d_mem_7_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_mem_7_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_fsa_fbus_xing_out_d_ridx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_fsa_fbus_xing_out_d_widx,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_d_safe_ridx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_safe_widx_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_fsa_fbus_xing_out_d_safe_source_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_fsa_fbus_xing_out_d_safe_sink_reset_n,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_tl_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_tl_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [15:0] auto_tl_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_tl_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_tl_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_tl_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_tl_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_tl_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_tl_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_tl_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_tl_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_tl_in_d_bits_corrupt	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  TLAsyncCrossingSource_a16d32s4k1z3u asource (	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:94:29]
    .clock                          (clock),
    .reset                          (reset),
    .auto_in_a_ready                (auto_tl_in_a_ready),
    .auto_in_a_valid                (auto_tl_in_a_valid),
    .auto_in_a_bits_opcode          (auto_tl_in_a_bits_opcode),
    .auto_in_a_bits_param           (auto_tl_in_a_bits_param),
    .auto_in_a_bits_size            (auto_tl_in_a_bits_size),
    .auto_in_a_bits_source          (auto_tl_in_a_bits_source),
    .auto_in_a_bits_address         (auto_tl_in_a_bits_address),
    .auto_in_a_bits_mask            (auto_tl_in_a_bits_mask),
    .auto_in_a_bits_data            (auto_tl_in_a_bits_data),
    .auto_in_a_bits_corrupt         (auto_tl_in_a_bits_corrupt),
    .auto_in_d_ready                (auto_tl_in_d_ready),
    .auto_in_d_valid                (auto_tl_in_d_valid),
    .auto_in_d_bits_opcode          (auto_tl_in_d_bits_opcode),
    .auto_in_d_bits_param           (auto_tl_in_d_bits_param),
    .auto_in_d_bits_size            (auto_tl_in_d_bits_size),
    .auto_in_d_bits_source          (auto_tl_in_d_bits_source),
    .auto_in_d_bits_sink            (auto_tl_in_d_bits_sink),
    .auto_in_d_bits_denied          (auto_tl_in_d_bits_denied),
    .auto_in_d_bits_data            (auto_tl_in_d_bits_data),
    .auto_in_d_bits_corrupt         (auto_tl_in_d_bits_corrupt),
    .auto_out_a_mem_0_opcode        (auto_fsa_fbus_xing_out_a_mem_0_opcode),
    .auto_out_a_mem_0_param         (auto_fsa_fbus_xing_out_a_mem_0_param),
    .auto_out_a_mem_0_size          (auto_fsa_fbus_xing_out_a_mem_0_size),
    .auto_out_a_mem_0_source        (auto_fsa_fbus_xing_out_a_mem_0_source),
    .auto_out_a_mem_0_address       (auto_fsa_fbus_xing_out_a_mem_0_address),
    .auto_out_a_mem_0_mask          (auto_fsa_fbus_xing_out_a_mem_0_mask),
    .auto_out_a_mem_0_data          (auto_fsa_fbus_xing_out_a_mem_0_data),
    .auto_out_a_mem_0_corrupt       (auto_fsa_fbus_xing_out_a_mem_0_corrupt),
    .auto_out_a_mem_1_opcode        (auto_fsa_fbus_xing_out_a_mem_1_opcode),
    .auto_out_a_mem_1_param         (auto_fsa_fbus_xing_out_a_mem_1_param),
    .auto_out_a_mem_1_size          (auto_fsa_fbus_xing_out_a_mem_1_size),
    .auto_out_a_mem_1_source        (auto_fsa_fbus_xing_out_a_mem_1_source),
    .auto_out_a_mem_1_address       (auto_fsa_fbus_xing_out_a_mem_1_address),
    .auto_out_a_mem_1_mask          (auto_fsa_fbus_xing_out_a_mem_1_mask),
    .auto_out_a_mem_1_data          (auto_fsa_fbus_xing_out_a_mem_1_data),
    .auto_out_a_mem_1_corrupt       (auto_fsa_fbus_xing_out_a_mem_1_corrupt),
    .auto_out_a_mem_2_opcode        (auto_fsa_fbus_xing_out_a_mem_2_opcode),
    .auto_out_a_mem_2_param         (auto_fsa_fbus_xing_out_a_mem_2_param),
    .auto_out_a_mem_2_size          (auto_fsa_fbus_xing_out_a_mem_2_size),
    .auto_out_a_mem_2_source        (auto_fsa_fbus_xing_out_a_mem_2_source),
    .auto_out_a_mem_2_address       (auto_fsa_fbus_xing_out_a_mem_2_address),
    .auto_out_a_mem_2_mask          (auto_fsa_fbus_xing_out_a_mem_2_mask),
    .auto_out_a_mem_2_data          (auto_fsa_fbus_xing_out_a_mem_2_data),
    .auto_out_a_mem_2_corrupt       (auto_fsa_fbus_xing_out_a_mem_2_corrupt),
    .auto_out_a_mem_3_opcode        (auto_fsa_fbus_xing_out_a_mem_3_opcode),
    .auto_out_a_mem_3_param         (auto_fsa_fbus_xing_out_a_mem_3_param),
    .auto_out_a_mem_3_size          (auto_fsa_fbus_xing_out_a_mem_3_size),
    .auto_out_a_mem_3_source        (auto_fsa_fbus_xing_out_a_mem_3_source),
    .auto_out_a_mem_3_address       (auto_fsa_fbus_xing_out_a_mem_3_address),
    .auto_out_a_mem_3_mask          (auto_fsa_fbus_xing_out_a_mem_3_mask),
    .auto_out_a_mem_3_data          (auto_fsa_fbus_xing_out_a_mem_3_data),
    .auto_out_a_mem_3_corrupt       (auto_fsa_fbus_xing_out_a_mem_3_corrupt),
    .auto_out_a_mem_4_opcode        (auto_fsa_fbus_xing_out_a_mem_4_opcode),
    .auto_out_a_mem_4_param         (auto_fsa_fbus_xing_out_a_mem_4_param),
    .auto_out_a_mem_4_size          (auto_fsa_fbus_xing_out_a_mem_4_size),
    .auto_out_a_mem_4_source        (auto_fsa_fbus_xing_out_a_mem_4_source),
    .auto_out_a_mem_4_address       (auto_fsa_fbus_xing_out_a_mem_4_address),
    .auto_out_a_mem_4_mask          (auto_fsa_fbus_xing_out_a_mem_4_mask),
    .auto_out_a_mem_4_data          (auto_fsa_fbus_xing_out_a_mem_4_data),
    .auto_out_a_mem_4_corrupt       (auto_fsa_fbus_xing_out_a_mem_4_corrupt),
    .auto_out_a_mem_5_opcode        (auto_fsa_fbus_xing_out_a_mem_5_opcode),
    .auto_out_a_mem_5_param         (auto_fsa_fbus_xing_out_a_mem_5_param),
    .auto_out_a_mem_5_size          (auto_fsa_fbus_xing_out_a_mem_5_size),
    .auto_out_a_mem_5_source        (auto_fsa_fbus_xing_out_a_mem_5_source),
    .auto_out_a_mem_5_address       (auto_fsa_fbus_xing_out_a_mem_5_address),
    .auto_out_a_mem_5_mask          (auto_fsa_fbus_xing_out_a_mem_5_mask),
    .auto_out_a_mem_5_data          (auto_fsa_fbus_xing_out_a_mem_5_data),
    .auto_out_a_mem_5_corrupt       (auto_fsa_fbus_xing_out_a_mem_5_corrupt),
    .auto_out_a_mem_6_opcode        (auto_fsa_fbus_xing_out_a_mem_6_opcode),
    .auto_out_a_mem_6_param         (auto_fsa_fbus_xing_out_a_mem_6_param),
    .auto_out_a_mem_6_size          (auto_fsa_fbus_xing_out_a_mem_6_size),
    .auto_out_a_mem_6_source        (auto_fsa_fbus_xing_out_a_mem_6_source),
    .auto_out_a_mem_6_address       (auto_fsa_fbus_xing_out_a_mem_6_address),
    .auto_out_a_mem_6_mask          (auto_fsa_fbus_xing_out_a_mem_6_mask),
    .auto_out_a_mem_6_data          (auto_fsa_fbus_xing_out_a_mem_6_data),
    .auto_out_a_mem_6_corrupt       (auto_fsa_fbus_xing_out_a_mem_6_corrupt),
    .auto_out_a_mem_7_opcode        (auto_fsa_fbus_xing_out_a_mem_7_opcode),
    .auto_out_a_mem_7_param         (auto_fsa_fbus_xing_out_a_mem_7_param),
    .auto_out_a_mem_7_size          (auto_fsa_fbus_xing_out_a_mem_7_size),
    .auto_out_a_mem_7_source        (auto_fsa_fbus_xing_out_a_mem_7_source),
    .auto_out_a_mem_7_address       (auto_fsa_fbus_xing_out_a_mem_7_address),
    .auto_out_a_mem_7_mask          (auto_fsa_fbus_xing_out_a_mem_7_mask),
    .auto_out_a_mem_7_data          (auto_fsa_fbus_xing_out_a_mem_7_data),
    .auto_out_a_mem_7_corrupt       (auto_fsa_fbus_xing_out_a_mem_7_corrupt),
    .auto_out_a_ridx                (auto_fsa_fbus_xing_out_a_ridx),
    .auto_out_a_widx                (auto_fsa_fbus_xing_out_a_widx),
    .auto_out_a_safe_ridx_valid     (auto_fsa_fbus_xing_out_a_safe_ridx_valid),
    .auto_out_a_safe_widx_valid     (auto_fsa_fbus_xing_out_a_safe_widx_valid),
    .auto_out_a_safe_source_reset_n (auto_fsa_fbus_xing_out_a_safe_source_reset_n),
    .auto_out_a_safe_sink_reset_n   (auto_fsa_fbus_xing_out_a_safe_sink_reset_n),
    .auto_out_d_mem_0_opcode        (auto_fsa_fbus_xing_out_d_mem_0_opcode),
    .auto_out_d_mem_0_size          (auto_fsa_fbus_xing_out_d_mem_0_size),
    .auto_out_d_mem_0_source        (auto_fsa_fbus_xing_out_d_mem_0_source),
    .auto_out_d_mem_0_denied        (auto_fsa_fbus_xing_out_d_mem_0_denied),
    .auto_out_d_mem_0_data          (auto_fsa_fbus_xing_out_d_mem_0_data),
    .auto_out_d_mem_0_corrupt       (auto_fsa_fbus_xing_out_d_mem_0_corrupt),
    .auto_out_d_mem_1_opcode        (auto_fsa_fbus_xing_out_d_mem_1_opcode),
    .auto_out_d_mem_1_size          (auto_fsa_fbus_xing_out_d_mem_1_size),
    .auto_out_d_mem_1_source        (auto_fsa_fbus_xing_out_d_mem_1_source),
    .auto_out_d_mem_1_denied        (auto_fsa_fbus_xing_out_d_mem_1_denied),
    .auto_out_d_mem_1_data          (auto_fsa_fbus_xing_out_d_mem_1_data),
    .auto_out_d_mem_1_corrupt       (auto_fsa_fbus_xing_out_d_mem_1_corrupt),
    .auto_out_d_mem_2_opcode        (auto_fsa_fbus_xing_out_d_mem_2_opcode),
    .auto_out_d_mem_2_size          (auto_fsa_fbus_xing_out_d_mem_2_size),
    .auto_out_d_mem_2_source        (auto_fsa_fbus_xing_out_d_mem_2_source),
    .auto_out_d_mem_2_denied        (auto_fsa_fbus_xing_out_d_mem_2_denied),
    .auto_out_d_mem_2_data          (auto_fsa_fbus_xing_out_d_mem_2_data),
    .auto_out_d_mem_2_corrupt       (auto_fsa_fbus_xing_out_d_mem_2_corrupt),
    .auto_out_d_mem_3_opcode        (auto_fsa_fbus_xing_out_d_mem_3_opcode),
    .auto_out_d_mem_3_size          (auto_fsa_fbus_xing_out_d_mem_3_size),
    .auto_out_d_mem_3_source        (auto_fsa_fbus_xing_out_d_mem_3_source),
    .auto_out_d_mem_3_denied        (auto_fsa_fbus_xing_out_d_mem_3_denied),
    .auto_out_d_mem_3_data          (auto_fsa_fbus_xing_out_d_mem_3_data),
    .auto_out_d_mem_3_corrupt       (auto_fsa_fbus_xing_out_d_mem_3_corrupt),
    .auto_out_d_mem_4_opcode        (auto_fsa_fbus_xing_out_d_mem_4_opcode),
    .auto_out_d_mem_4_size          (auto_fsa_fbus_xing_out_d_mem_4_size),
    .auto_out_d_mem_4_source        (auto_fsa_fbus_xing_out_d_mem_4_source),
    .auto_out_d_mem_4_denied        (auto_fsa_fbus_xing_out_d_mem_4_denied),
    .auto_out_d_mem_4_data          (auto_fsa_fbus_xing_out_d_mem_4_data),
    .auto_out_d_mem_4_corrupt       (auto_fsa_fbus_xing_out_d_mem_4_corrupt),
    .auto_out_d_mem_5_opcode        (auto_fsa_fbus_xing_out_d_mem_5_opcode),
    .auto_out_d_mem_5_size          (auto_fsa_fbus_xing_out_d_mem_5_size),
    .auto_out_d_mem_5_source        (auto_fsa_fbus_xing_out_d_mem_5_source),
    .auto_out_d_mem_5_denied        (auto_fsa_fbus_xing_out_d_mem_5_denied),
    .auto_out_d_mem_5_data          (auto_fsa_fbus_xing_out_d_mem_5_data),
    .auto_out_d_mem_5_corrupt       (auto_fsa_fbus_xing_out_d_mem_5_corrupt),
    .auto_out_d_mem_6_opcode        (auto_fsa_fbus_xing_out_d_mem_6_opcode),
    .auto_out_d_mem_6_size          (auto_fsa_fbus_xing_out_d_mem_6_size),
    .auto_out_d_mem_6_source        (auto_fsa_fbus_xing_out_d_mem_6_source),
    .auto_out_d_mem_6_denied        (auto_fsa_fbus_xing_out_d_mem_6_denied),
    .auto_out_d_mem_6_data          (auto_fsa_fbus_xing_out_d_mem_6_data),
    .auto_out_d_mem_6_corrupt       (auto_fsa_fbus_xing_out_d_mem_6_corrupt),
    .auto_out_d_mem_7_opcode        (auto_fsa_fbus_xing_out_d_mem_7_opcode),
    .auto_out_d_mem_7_size          (auto_fsa_fbus_xing_out_d_mem_7_size),
    .auto_out_d_mem_7_source        (auto_fsa_fbus_xing_out_d_mem_7_source),
    .auto_out_d_mem_7_denied        (auto_fsa_fbus_xing_out_d_mem_7_denied),
    .auto_out_d_mem_7_data          (auto_fsa_fbus_xing_out_d_mem_7_data),
    .auto_out_d_mem_7_corrupt       (auto_fsa_fbus_xing_out_d_mem_7_corrupt),
    .auto_out_d_ridx                (auto_fsa_fbus_xing_out_d_ridx),
    .auto_out_d_widx                (auto_fsa_fbus_xing_out_d_widx),
    .auto_out_d_safe_ridx_valid     (auto_fsa_fbus_xing_out_d_safe_ridx_valid),
    .auto_out_d_safe_widx_valid     (auto_fsa_fbus_xing_out_d_safe_widx_valid),
    .auto_out_d_safe_source_reset_n (auto_fsa_fbus_xing_out_d_safe_source_reset_n),
    .auto_out_d_safe_sink_reset_n   (auto_fsa_fbus_xing_out_d_safe_sink_reset_n)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/AsyncCrossing.scala:94:29]
endmodule

