// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module TLToAXI4(	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [8:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [15:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [8:0]  auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_aw_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_aw_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_aw_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_aw_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_aw_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [8:0]  auto_out_aw_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_w_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_w_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_w_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_w_bits_strb,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_b_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [8:0]  auto_out_b_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_ar_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_ar_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_ar_bits_id,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [15:0] auto_out_ar_bits_addr,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_ar_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_ar_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [8:0]  auto_out_ar_bits_echo_tl_state_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_r_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_r_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_out_r_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_r_bits_echo_tl_state_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [8:0]  auto_out_r_bits_echo_tl_state_source	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire        idStall_0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:286:34]
  wire        _queue_arw_deq_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _queue_arw_deq_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _queue_arw_deq_q_io_deq_bits_id;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [15:0] _queue_arw_deq_q_io_deq_bits_addr;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0]  _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [8:0]  _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _queue_arw_deq_q_io_deq_bits_wen;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _nodeOut_w_deq_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  reg         r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27]
  wire [12:0] _out_arw_bits_len_T = 13'h3FF << auto_in_a_bits_size;	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:71]
  wire        stall = idStall_0 & ~r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :231:25, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49, :286:34]
  wire        nodeIn_a_ready = ~stall & (auto_in_a_bits_opcode[2] | _nodeOut_w_deq_q_io_enq_ready) & _queue_arw_deq_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49, :206:{21,28,34}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        out_arw_valid = ~stall & auto_in_a_valid & (auto_in_a_bits_opcode[2] | _nodeOut_w_deq_q_io_enq_ready);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:37, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49, :206:21, :207:{31,45,51}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  reg  [2:0]  b_delay;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:219:24]
  wire        _r_wins_T_1 = auto_out_r_valid & b_delay != 3'h7;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:219:24, :225:{33,44}]
  wire        nodeOut_b_ready = auto_in_d_ready & ~_r_wins_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:33, :228:{33,36}]
  wire        nodeIn_d_valid = _r_wins_T_1 ? auto_out_r_valid : auto_out_b_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:33, :229:24]
  wire [2:0]  nodeIn_d_bits_opcode = {2'h0, _r_wins_T_1};	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:33, :255:23]
  wire [1:0]  nodeIn_d_bits_size = _r_wins_T_1 ? auto_out_r_bits_echo_tl_state_size[1:0] : auto_out_b_bits_echo_tl_state_size[1:0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:795:15, :813:15, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:33, :255:23]
  wire [8:0]  nodeIn_d_bits_source = _r_wins_T_1 ? auto_out_r_bits_echo_tl_state_source : auto_out_b_bits_echo_tl_state_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:225:33, :255:23]
  reg  [9:0]  count;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
  reg         write;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:273:24]
  wire        inc = _queue_arw_deq_q_io_enq_ready & out_arw_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:207:{31,45}, src/main/scala/chisel3/util/Decoupled.scala:51:35, :362:21]
  wire        _dec_T_1 = auto_in_d_ready & nodeIn_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:229:24, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      if (~reset & {~_dec_T_1, count} == 11'h0) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :280:{16,17,22,31}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $error("Assertion failed\n    at ToAXI4.scala:280 assert (!dec || count =/= 0.U)        // underflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:280:16]
      end
      if (~reset & ~(~inc | count != 10'h200)) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :280:16, :281:{16,17,22,31}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $error("Assertion failed\n    at ToAXI4.scala:281 assert (!inc || count =/= maxCount.U) // overflow\n");	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
          $fatal;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:281:16]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign idStall_0 = (|count) & write != ~(auto_in_a_bits_opcode[2]) | count == 10'h200;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :273:24, :274:26, :285:50, :286:{21,34,44}]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      r_counter <= 1'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      count <= 10'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      r_counter <= (~(nodeIn_a_ready & auto_in_a_valid) | r_counter - 1'h1) & r_counter;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, :230:28, :235:17, :236:15, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:206:{28,34}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      count <= count + {9'h0, inc} - {9'h0, _dec_T_1};	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:272:28, :278:{24,37}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
    end
    b_delay <= auto_out_b_valid & ~nodeOut_b_ready ? b_delay + 3'h1 : 3'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:219:24, :220:{25,28,42}, :221:{17,28}, :223:17, :228:33]
    if (inc)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      write <= ~(auto_in_a_bits_opcode[2]);	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:273:24]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        r_counter = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
        b_delay = _RANDOM[/*Zero width*/ 1'b0][5:3];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :219:24]
        count = _RANDOM[/*Zero width*/ 1'b0][17:8];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :272:28]
        write = _RANDOM[/*Zero width*/ 1'b0][18];	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:229:27, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :273:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_11 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (nodeIn_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:206:{28,34}]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (nodeIn_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:229:24]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
    .io_in_d_bits_size    (nodeIn_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
    .io_in_d_bits_source  (nodeIn_d_bits_source)	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:255:23]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  Queue1_AXI4BundleW nodeOut_w_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_ready     (_nodeOut_w_deq_q_io_enq_ready),
    .io_enq_valid     (~stall & auto_in_a_valid & ~(auto_in_a_bits_opcode[2]) & _queue_arw_deq_q_io_enq_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}, generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:205:49, :206:21, :209:{29,43,54}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_enq_bits_data (auto_in_a_bits_data),
    .io_enq_bits_strb (auto_in_a_bits_mask),
    .io_deq_ready     (auto_out_w_ready),
    .io_deq_valid     (auto_out_w_valid),
    .io_deq_bits_data (auto_out_w_bits_data),
    .io_deq_bits_strb (auto_out_w_bits_strb)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  Queue1_AXI4BundleARW queue_arw_deq_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                            (clock),
    .reset                            (reset),
    .io_enq_ready                     (_queue_arw_deq_q_io_enq_ready),
    .io_enq_valid                     (out_arw_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:207:{31,45}]
    .io_enq_bits_addr                 (auto_in_a_bits_address),
    .io_enq_bits_len                  (~(_out_arw_bits_len_T[9:2])),	// @[generators/rocket-chip/src/main/scala/util/package.scala:243:{46,71,76}]
    .io_enq_bits_size                 ({1'h0, auto_in_a_bits_size[1] ? 2'h2 : auto_in_a_bits_size}),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :175:{17,23,31}]
    .io_enq_bits_echo_tl_state_size   ({2'h0, auto_in_a_bits_size}),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:189:22]
    .io_enq_bits_echo_tl_state_source (auto_in_a_bits_source),
    .io_enq_bits_wen                  (~(auto_in_a_bits_opcode[2])),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:92:{28,37}]
    .io_deq_ready                     (_queue_arw_deq_q_io_deq_bits_wen ? auto_out_aw_ready : auto_out_ar_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:163:29, src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_deq_valid                     (_queue_arw_deq_q_io_deq_valid),
    .io_deq_bits_id                   (_queue_arw_deq_q_io_deq_bits_id),
    .io_deq_bits_addr                 (_queue_arw_deq_q_io_deq_bits_addr),
    .io_deq_bits_size                 (auto_out_ar_bits_size),
    .io_deq_bits_echo_tl_state_size   (_queue_arw_deq_q_io_deq_bits_echo_tl_state_size),
    .io_deq_bits_echo_tl_state_source (_queue_arw_deq_q_io_deq_bits_echo_tl_state_source),
    .io_deq_bits_wen                  (_queue_arw_deq_q_io_deq_bits_wen)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_in_a_ready = nodeIn_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :206:{28,34}]
  assign auto_in_d_valid = nodeIn_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :229:24]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_size = nodeIn_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_source = nodeIn_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :255:23]
  assign auto_in_d_bits_data = auto_out_r_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9]
  assign auto_out_aw_valid = _queue_arw_deq_q_io_deq_valid & _queue_arw_deq_q_io_deq_bits_wen;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :162:39, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_id = _queue_arw_deq_q_io_deq_bits_id;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_addr = _queue_arw_deq_q_io_deq_bits_addr;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_echo_tl_state_size = _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_aw_bits_echo_tl_state_source = _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_b_ready = nodeOut_b_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :228:33]
  assign auto_out_ar_valid = _queue_arw_deq_q_io_deq_valid & ~_queue_arw_deq_q_io_deq_bits_wen;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :161:{39,42}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_id = _queue_arw_deq_q_io_deq_bits_id;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_addr = _queue_arw_deq_q_io_deq_bits_addr;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_echo_tl_state_size = _queue_arw_deq_q_io_deq_bits_echo_tl_state_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_ar_bits_echo_tl_state_source = _queue_arw_deq_q_io_deq_bits_echo_tl_state_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_out_r_ready = auto_in_d_ready & _r_wins_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/ToAXI4.scala:103:9, :225:33, :227:33]
endmodule

