// Generated by CIRCT firtool-1.75.0
module TLZero(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [9:0]  auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [14:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [9:0]  auto_in_d_bits_source	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire            _a_q_io_enq_ready;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire            _a_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [2:0]      _a_q_io_deq_bits_opcode;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [1:0]      _a_q_io_deq_bits_size;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [9:0]      _a_q_io_deq_bits_source;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [7:0][2:0] _GEN = '{3'h4, 3'h4, 3'h2, 3'h1, 3'h1, 3'h1, 3'h0, 3'h0};
  wire [2:0]      nodeIn_d_bits_opcode = _GEN[_a_q_io_deq_bits_opcode];	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:41:22, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  TLMonitor_6 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (clock),
    .reset                (reset),
    .io_in_a_ready        (_a_q_io_enq_ready),	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (_a_q_io_deq_valid),	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:41:22]
    .io_in_d_bits_size    (_a_q_io_deq_bits_size),	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .io_in_d_bits_source  (_a_q_io_deq_bits_source)	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  Queue2_TLBundleA_a15d64s10k1z2u a_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock               (clock),
    .reset               (reset),
    .io_enq_ready        (_a_q_io_enq_ready),
    .io_enq_valid        (auto_in_a_valid),
    .io_enq_bits_opcode  (auto_in_a_bits_opcode),
    .io_enq_bits_param   (auto_in_a_bits_param),
    .io_enq_bits_size    (auto_in_a_bits_size),
    .io_enq_bits_source  (auto_in_a_bits_source),
    .io_enq_bits_address (auto_in_a_bits_address),
    .io_enq_bits_mask    (auto_in_a_bits_mask),
    .io_enq_bits_data    (auto_in_a_bits_data),
    .io_enq_bits_corrupt (auto_in_a_bits_corrupt),
    .io_deq_ready        (auto_in_d_ready),
    .io_deq_valid        (_a_q_io_deq_valid),
    .io_deq_bits_opcode  (_a_q_io_deq_bits_opcode),
    .io_deq_bits_size    (_a_q_io_deq_bits_size),
    .io_deq_bits_source  (_a_q_io_deq_bits_source)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_in_a_ready = _a_q_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_in_d_valid = _a_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9, :41:22]
  assign auto_in_d_bits_size = _a_q_io_deq_bits_size;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign auto_in_d_bits_source = _a_q_io_deq_bits_source;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Zero.scala:33:9, src/main/scala/chisel3/util/Decoupled.scala:362:21]
endmodule

