// Generated by CIRCT firtool-1.75.0
module banks_subBanks_sram_mem_13(	
  input  [4:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [63:0] R0_data,
  input  [4:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [63:0] W0_data
);

  banks_subBanks_sram_mem_0_ext banks_subBanks_sram_mem_0_ext (	
    .R0_addr (R0_addr),
    .R0_en   (R0_en),
    .R0_clk  (R0_clk),
    .R0_data (R0_data),
    .W0_addr (W0_addr),
    .W0_en   (W0_en),
    .W0_clk  (W0_clk),
    .W0_data (W0_data)
  );	
endmodule

