// Generated by CIRCT firtool-1.75.0
module banks_subBanks_sram_mem(	
  input  [6:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [63:0] R0_data,
  input  [6:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [63:0] W0_data
);


  reg [63:0] mem [0:127];
  reg [63:0] rdata_reg;

  always @(posedge W0_clk) begin
    if (W0_en) begin
      mem[W0_addr] <= W0_data;
    end
  end

  always @(posedge R0_clk) begin
    if (R0_en) begin
      rdata_reg <= mem[R0_addr];
    end
  end

  assign R0_data = rdata_reg;

endmodule

