// Generated by CIRCT firtool-1.75.0
module FMA(	
  input  [31:0] io_a,	
  input  [31:0] io_c,	
  output [31:0] io_out	
);

  wire        _rawFMA_io_out_isZero;	
  wire        _rawFMA_io_out_isInf;	
  wire        _rawFMA_io_out_isNaN;	
  wire        _rawFMA_io_out_sign;	
  wire [10:0] _rawFMA_io_out_exp;	
  wire [25:0] _rawFMA_io_out_mantissa;	
  wire [23:0] io_out_roundedMantissa = {1'h0, _rawFMA_io_out_mantissa[24:2]} + {23'h0, _rawFMA_io_out_mantissa[1] & _rawFMA_io_out_mantissa[0] | _rawFMA_io_out_mantissa[1] & ~(_rawFMA_io_out_mantissa[0]) & _rawFMA_io_out_mantissa[2]};	
  wire [11:0] io_out_roundedExp = {_rawFMA_io_out_exp[10], _rawFMA_io_out_exp} + {11'h0, io_out_roundedMantissa[23]};	
  wire        io_out_overflow = $signed(io_out_roundedExp) > 12'sh7F;	
  wire        io_out_underflow = $signed(io_out_roundedExp) < -12'sh7E;	
  RawFloat_FMA rawFMA (	
    .io_a_isZero     (io_a[30:23] == 8'h0),	
    .io_a_isInf      ((&(io_a[30:23])) & ~(|(io_a[22:0]))),	
    .io_a_isNaN      ((&(io_a[30:23])) & (|(io_a[22:0]))),	
    .io_a_sign       (io_a[31]),	
    .io_a_exp        ({1'h0, io_a[30:23]} - 9'h7F),	
    .io_a_mantissa   ({1'h1, io_a[22:0]}),	
    .io_b_isZero     (1'h0),
    .io_b_isInf      (1'h0),
    .io_b_isNaN      (1'h0),
    .io_b_sign       (1'h0),
    .io_b_exp        (9'h0),	
    .io_b_mantissa   (24'h800000),	
    .io_c_isZero     (io_c[30:23] == 8'h0),	
    .io_c_isInf      ((&(io_c[30:23])) & ~(|(io_c[22:0]))),	
    .io_c_isNaN      ((&(io_c[30:23])) & (|(io_c[22:0]))),	
    .io_c_sign       (io_c[31]),	
    .io_c_exp        ({1'h0, io_c[30:23]} - 9'h7F),	
    .io_c_mantissa   ({1'h1, io_c[22:0]}),	
    .io_out_isZero   (_rawFMA_io_out_isZero),
    .io_out_isInf    (_rawFMA_io_out_isInf),
    .io_out_isNaN    (_rawFMA_io_out_isNaN),
    .io_out_sign     (_rawFMA_io_out_sign),
    .io_out_exp      (_rawFMA_io_out_exp),
    .io_out_mantissa (_rawFMA_io_out_mantissa)
  );	
  assign io_out = {_rawFMA_io_out_sign & ~_rawFMA_io_out_isNaN, _rawFMA_io_out_isInf | _rawFMA_io_out_isNaN | io_out_overflow ? 8'hFF : _rawFMA_io_out_isZero | io_out_underflow ? 8'h0 : io_out_roundedExp[7:0] + 8'h7F, _rawFMA_io_out_isNaN ? 23'h400000 : _rawFMA_io_out_isZero | _rawFMA_io_out_isInf | io_out_underflow | io_out_overflow ? 23'h0 : io_out_roundedMantissa[22:0]};	
endmodule

