// Generated by CIRCT firtool-1.75.0
module FPAccUnit(	
  input         clock,	
  input         reset,	
  input         io_in_a_sign,	
  input  [7:0]  io_in_a_exp,	
  input  [22:0] io_in_a_mantissa,	
  input         io_in_b_sign,	
  input  [7:0]  io_in_b_exp,	
  input  [22:0] io_in_b_mantissa,	
  input         io_in_c_sign,	
  input  [7:0]  io_in_c_exp,	
  input  [22:0] io_in_c_mantissa,	
  input         io_in_cmd,	
  output        io_out_accType_sign,	
  output [7:0]  io_out_accType_exp,	
  output [22:0] io_out_accType_mantissa,	
  input         multiCycleIO_reciprocal_in_valid,	
  output        multiCycleIO_reciprocal_out_valid	
);

  wire        _reciprocal_io_fma_rawA_isZero;	
  wire        _reciprocal_io_fma_rawA_isInf;	
  wire        _reciprocal_io_fma_rawA_isNaN;	
  wire        _reciprocal_io_fma_rawA_sign;	
  wire [8:0]  _reciprocal_io_fma_rawA_exp;	
  wire [23:0] _reciprocal_io_fma_rawA_mantissa;	
  wire        _reciprocal_io_fma_rawB_isZero;	
  wire        _reciprocal_io_fma_rawB_isInf;	
  wire        _reciprocal_io_fma_rawB_isNaN;	
  wire        _reciprocal_io_fma_rawB_sign;	
  wire [8:0]  _reciprocal_io_fma_rawB_exp;	
  wire [23:0] _reciprocal_io_fma_rawB_mantissa;	
  wire        _reciprocal_io_fma_rawC_isZero;	
  wire [8:0]  _reciprocal_io_fma_rawC_exp;	
  wire [23:0] _reciprocal_io_fma_rawC_mantissa;	
  wire        _mulAddExp2_io_out_isZero;	
  wire        _mulAddExp2_io_out_isInf;	
  wire        _mulAddExp2_io_out_isNaN;	
  wire        _mulAddExp2_io_out_sign;	
  wire [10:0] _mulAddExp2_io_out_exp;	
  wire [25:0] _mulAddExp2_io_out_mantissa;	
  wire [23:0] io_out_accType_roundedMantissa = {1'h0, _mulAddExp2_io_out_mantissa[24:2]} + {23'h0, _mulAddExp2_io_out_mantissa[1] & _mulAddExp2_io_out_mantissa[0] | _mulAddExp2_io_out_mantissa[1] & ~(_mulAddExp2_io_out_mantissa[0]) & _mulAddExp2_io_out_mantissa[2]};	
  wire [11:0] io_out_accType_roundedExp = {_mulAddExp2_io_out_exp[10], _mulAddExp2_io_out_exp} + {11'h0, io_out_accType_roundedMantissa[23]};	
  wire        io_out_accType_overflow = $signed(io_out_accType_roundedExp) > 12'sh7F;	
  wire        io_out_accType_underflow = $signed(io_out_accType_roundedExp) < -12'sh7E;	
  wire        io_out_accType_resSign = _mulAddExp2_io_out_sign & ~_mulAddExp2_io_out_isNaN;	
  wire [7:0]  io_out_accType_resExp = _mulAddExp2_io_out_isInf | _mulAddExp2_io_out_isNaN | io_out_accType_overflow ? 8'hFF : _mulAddExp2_io_out_isZero | io_out_accType_underflow ? 8'h0 : io_out_accType_roundedExp[7:0] + 8'h7F;	
  wire [22:0] io_out_accType_resMantissa = _mulAddExp2_io_out_isNaN ? 23'h400000 : _mulAddExp2_io_out_isZero | _mulAddExp2_io_out_isInf | io_out_accType_underflow | io_out_accType_overflow ? 23'h0 : io_out_accType_roundedMantissa[22:0];	
  RawFloat_MulAddExp2_1 mulAddExp2 (	
    .io_in_exp2       (~multiCycleIO_reciprocal_in_valid & io_in_cmd),	
    .io_in_a_isZero   (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_isZero : io_in_a_exp == 8'h0),	
    .io_in_a_isInf    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_isInf : (&io_in_a_exp) & ~(|io_in_a_mantissa)),	
    .io_in_a_isNaN    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_isNaN : (&io_in_a_exp) & (|io_in_a_mantissa)),	
    .io_in_a_sign     (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_sign : io_in_a_sign),	
    .io_in_a_exp      (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_exp : {1'h0, io_in_a_exp} - 9'h7F),	
    .io_in_a_mantissa (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawA_mantissa : {1'h1, io_in_a_mantissa}),	
    .io_in_b_isZero   (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_isZero : io_in_b_exp == 8'h0),	
    .io_in_b_isInf    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_isInf : (&io_in_b_exp) & ~(|io_in_b_mantissa)),	
    .io_in_b_isNaN    (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_isNaN : (&io_in_b_exp) & (|io_in_b_mantissa)),	
    .io_in_b_sign     (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_sign : io_in_b_sign),	
    .io_in_b_exp      (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_exp : {1'h0, io_in_b_exp} - 9'h7F),	
    .io_in_b_mantissa (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawB_mantissa : {1'h1, io_in_b_mantissa}),	
    .io_in_c_isZero   (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawC_isZero : io_in_c_exp == 8'h0),	
    .io_in_c_isInf    (~multiCycleIO_reciprocal_in_valid & (&io_in_c_exp) & ~(|io_in_c_mantissa)),	
    .io_in_c_isNaN    (~multiCycleIO_reciprocal_in_valid & (&io_in_c_exp) & (|io_in_c_mantissa)),	
    .io_in_c_sign     (~multiCycleIO_reciprocal_in_valid & io_in_c_sign),	
    .io_in_c_exp      (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawC_exp : {1'h0, io_in_c_exp} - 9'h7F),	
    .io_in_c_mantissa (multiCycleIO_reciprocal_in_valid ? _reciprocal_io_fma_rawC_mantissa : {1'h1, io_in_c_mantissa}),	
    .io_out_isZero    (_mulAddExp2_io_out_isZero),
    .io_out_isInf     (_mulAddExp2_io_out_isInf),
    .io_out_isNaN     (_mulAddExp2_io_out_isNaN),
    .io_out_sign      (_mulAddExp2_io_out_sign),
    .io_out_exp       (_mulAddExp2_io_out_exp),
    .io_out_mantissa  (_mulAddExp2_io_out_mantissa)
  );	
  Reciprocal reciprocal (	
    .clock                 (clock),
    .reset                 (reset),
    .io_in                 ({io_in_a_sign, io_in_a_exp, io_in_a_mantissa}),	
    .io_in_valid           (multiCycleIO_reciprocal_in_valid),
    .io_out_valid          (multiCycleIO_reciprocal_out_valid),
    .io_fma_rawA_isZero    (_reciprocal_io_fma_rawA_isZero),
    .io_fma_rawA_isInf     (_reciprocal_io_fma_rawA_isInf),
    .io_fma_rawA_isNaN     (_reciprocal_io_fma_rawA_isNaN),
    .io_fma_rawA_sign      (_reciprocal_io_fma_rawA_sign),
    .io_fma_rawA_exp       (_reciprocal_io_fma_rawA_exp),
    .io_fma_rawA_mantissa  (_reciprocal_io_fma_rawA_mantissa),
    .io_fma_rawB_isZero    (_reciprocal_io_fma_rawB_isZero),
    .io_fma_rawB_isInf     (_reciprocal_io_fma_rawB_isInf),
    .io_fma_rawB_isNaN     (_reciprocal_io_fma_rawB_isNaN),
    .io_fma_rawB_sign      (_reciprocal_io_fma_rawB_sign),
    .io_fma_rawB_exp       (_reciprocal_io_fma_rawB_exp),
    .io_fma_rawB_mantissa  (_reciprocal_io_fma_rawB_mantissa),
    .io_fma_rawC_isZero    (_reciprocal_io_fma_rawC_isZero),
    .io_fma_rawC_exp       (_reciprocal_io_fma_rawC_exp),
    .io_fma_rawC_mantissa  (_reciprocal_io_fma_rawC_mantissa),
    .io_fma_rounded_result ({io_out_accType_resSign, io_out_accType_resExp, io_out_accType_resMantissa})	
  );	
  assign io_out_accType_sign = io_out_accType_resSign;	
  assign io_out_accType_exp = io_out_accType_resExp;	
  assign io_out_accType_mantissa = io_out_accType_resMantissa;	
endmodule

