// Generated by CIRCT firtool-1.75.0
module FPCmpUnit(	
  input         io_in_a_sign,	
  input  [7:0]  io_in_a_exp,	
  input  [22:0] io_in_a_mantissa,	
  input         io_in_b_sign,	
  input  [7:0]  io_in_b_exp,	
  input  [22:0] io_in_b_mantissa,	
  output        io_out_max_sign,	
  output [7:0]  io_out_max_exp,	
  output [22:0] io_out_max_mantissa,	
  output        io_out_diff_sign,	
  output [7:0]  io_out_diff_exp,	
  output [22:0] io_out_diff_mantissa	
);

  wire [31:0] _fma_io_out;	
  FMA fma (	
    .io_a   ({io_in_a_sign, io_in_a_exp, io_in_a_mantissa}),	
    .io_c   ({~io_in_b_sign, io_in_b_exp, io_in_b_mantissa}),	
    .io_out (_fma_io_out)
  );	
  assign io_out_max_sign = _fma_io_out[31] ? io_in_b_sign : io_in_a_sign;	
  assign io_out_max_exp = _fma_io_out[31] ? io_in_b_exp : io_in_a_exp;	
  assign io_out_max_mantissa = _fma_io_out[31] ? io_in_b_mantissa : io_in_a_mantissa;	
  assign io_out_diff_sign = _fma_io_out[31];	
  assign io_out_diff_exp = _fma_io_out[30:23];	
  assign io_out_diff_mantissa = _fma_io_out[22:0];	
endmodule

