// Generated by CIRCT firtool-1.75.0
module FPMacUnit(	
  input         io_in_a_sign,	
  input  [4:0]  io_in_a_exp,	
  input  [9:0]  io_in_a_mantissa,	
  input         io_in_b_sign,	
  input  [4:0]  io_in_b_exp,	
  input  [9:0]  io_in_b_mantissa,	
  input         io_in_c_sign,	
  input  [7:0]  io_in_c_exp,	
  input  [22:0] io_in_c_mantissa,	
  input         io_in_cmd,	
  output        io_out_accType_sign,	
  output [7:0]  io_out_accType_exp,	
  output [22:0] io_out_accType_mantissa,	
  output        io_out_elemType_sign,	
  output [4:0]  io_out_elemType_exp,	
  output [9:0]  io_out_elemType_mantissa,	
  output        io_out_exp2	
);

  wire        _mulAddExp2_io_out_isZero;	
  wire        _mulAddExp2_io_out_isInf;	
  wire        _mulAddExp2_io_out_isNaN;	
  wire        _mulAddExp2_io_out_sign;	
  wire [8:0]  _mulAddExp2_io_out_exp;	
  wire [25:0] _mulAddExp2_io_out_mantissa;	
  wire [2:0]  _mulAddExp2_io_exp2_frac_msb;	
  wire [23:0] io_out_accType_roundedMantissa = {1'h0, _mulAddExp2_io_out_mantissa[24:2]} + {23'h0, _mulAddExp2_io_out_mantissa[1] & _mulAddExp2_io_out_mantissa[0] | _mulAddExp2_io_out_mantissa[1] & ~(_mulAddExp2_io_out_mantissa[0]) & _mulAddExp2_io_out_mantissa[2]};	
  wire [9:0]  _GEN = {_mulAddExp2_io_out_exp[8], _mulAddExp2_io_out_exp};	
  wire [9:0]  io_out_accType_roundedExp = _GEN + {9'h0, io_out_accType_roundedMantissa[23]};	
  wire        io_out_accType_overflow = $signed(io_out_accType_roundedExp) > 10'sh7F;	
  wire        io_out_accType_underflow = $signed(io_out_accType_roundedExp) < -10'sh7E;	
  wire        _io_out_elemType_resExp_T = _mulAddExp2_io_out_isInf | _mulAddExp2_io_out_isNaN;	
  wire        _io_out_elemType_resMantissa_T = _mulAddExp2_io_out_isZero | _mulAddExp2_io_out_isInf;	
  wire [10:0] io_out_elemType_roundedMantissa = {1'h0, _mulAddExp2_io_out_mantissa[24:15]} + {10'h0, _mulAddExp2_io_out_mantissa[14] & (|(_mulAddExp2_io_out_mantissa[13:0])) | _mulAddExp2_io_out_mantissa[14] & ~(|(_mulAddExp2_io_out_mantissa[13:0])) & _mulAddExp2_io_out_mantissa[15]};	
  wire [9:0]  io_out_elemType_roundedExp = _GEN + {9'h0, io_out_elemType_roundedMantissa[10]};	
  wire        io_out_elemType_overflow = $signed(io_out_elemType_roundedExp) > 10'shF;	
  wire        io_out_elemType_underflow = $signed(io_out_elemType_roundedExp) < -10'shE;	
  RawFloat_MulAddExp2 mulAddExp2 (	
    .io_in_exp2       (io_in_cmd),
    .io_in_a_isZero   (io_in_a_exp == 5'h0),	
    .io_in_a_isInf    ((&io_in_a_exp) & ~(|io_in_a_mantissa)),	
    .io_in_a_isNaN    ((&io_in_a_exp) & (|io_in_a_mantissa)),	
    .io_in_a_sign     (io_in_a_sign),
    .io_in_a_exp      ({1'h0, io_in_a_exp} - 6'hF),	
    .io_in_a_mantissa ({1'h1, io_in_a_mantissa}),	
    .io_in_b_isZero   (io_in_b_exp == 5'h0),	
    .io_in_b_isInf    ((&io_in_b_exp) & ~(|io_in_b_mantissa)),	
    .io_in_b_isNaN    ((&io_in_b_exp) & (|io_in_b_mantissa)),	
    .io_in_b_sign     (io_in_b_sign),
    .io_in_b_exp      ({1'h0, io_in_b_exp} - 6'hF),	
    .io_in_b_mantissa ({1'h1, io_in_b_mantissa}),	
    .io_in_c_isZero   (~io_in_cmd & io_in_c_exp == 8'h0),	
    .io_in_c_isInf    (~io_in_cmd & (&io_in_c_exp) & ~(|io_in_c_mantissa)),	
    .io_in_c_isNaN    (~io_in_cmd & (&io_in_c_exp) & (|io_in_c_mantissa)),	
    .io_in_c_sign     (io_in_c_sign),
    .io_in_c_exp      (io_in_cmd ? {8'h3F, io_in_c_exp[0]} - 9'h7F : {1'h0, io_in_c_exp} - 9'h7F),	
    .io_in_c_mantissa ({1'h1, io_in_c_mantissa}),	
    .io_out_isZero    (_mulAddExp2_io_out_isZero),
    .io_out_isInf     (_mulAddExp2_io_out_isInf),
    .io_out_isNaN     (_mulAddExp2_io_out_isNaN),
    .io_out_sign      (_mulAddExp2_io_out_sign),
    .io_out_exp       (_mulAddExp2_io_out_exp),
    .io_out_mantissa  (_mulAddExp2_io_out_mantissa),
    .io_exp2_frac_msb (_mulAddExp2_io_exp2_frac_msb)
  );	
  assign io_out_accType_sign = _mulAddExp2_io_out_sign & ~_mulAddExp2_io_out_isNaN;	
  assign io_out_accType_exp = _io_out_elemType_resExp_T | io_out_accType_overflow ? 8'hFF : _mulAddExp2_io_out_isZero | io_out_accType_underflow ? 8'h0 : io_out_accType_roundedExp[7:0] + 8'h7F;	
  assign io_out_accType_mantissa = _mulAddExp2_io_out_isNaN ? 23'h400000 : _io_out_elemType_resMantissa_T | io_out_accType_underflow | io_out_accType_overflow ? 23'h0 : io_out_accType_roundedMantissa[22:0];	
  assign io_out_elemType_sign = _mulAddExp2_io_out_sign & ~_mulAddExp2_io_out_isNaN;	
  assign io_out_elemType_exp = _io_out_elemType_resExp_T | io_out_elemType_overflow ? 5'h1F : _mulAddExp2_io_out_isZero | io_out_elemType_underflow ? 5'h0 : io_out_elemType_roundedExp[4:0] + 5'hF;	
  assign io_out_elemType_mantissa = _mulAddExp2_io_out_isNaN ? 10'h200 : _io_out_elemType_resMantissa_T | io_out_elemType_underflow | io_out_elemType_overflow ? 10'h0 : io_out_elemType_roundedMantissa[9:0];	
  assign io_out_exp2 = io_in_cmd & io_in_c_exp[3:1] == _mulAddExp2_io_exp2_frac_msb;	
endmodule

