// Generated by CIRCT firtool-1.75.0
module RawFloat_SplitIF_1(	
  input         io_in_isZero,	
  input         io_in_isInf,	
  input         io_in_isNaN,	
  input         io_in_sign,	
  input  [8:0]  io_in_exp,	
  input  [23:0] io_in_mantissa,	
  output [8:0]  io_outInt,	
  output [2:0]  io_outFracMSBs,	
  output        io_outRawFloat_isZero,	
  output        io_outRawFloat_isInf,	
  output        io_outRawFloat_isNaN,	
  output        io_outRawFloat_sign,	
  output [8:0]  io_outRawFloat_exp,	
  output [23:0] io_outRawFloat_mantissa	
);

  wire        _GEN = $signed(io_in_exp) < 9'sh0;	
  wire [8:0]  _rightShiftAmt_T = 9'h1FF - io_in_exp;	
  wire [23:0] fracAlignedToMinusOne = io_in_mantissa >> _rightShiftAmt_T[1:0];	
  wire [30:0] shiftedMantissa = {7'h0, io_in_mantissa} << io_in_exp[2:0];	
  wire [8:0]  _GEN_0 = {1'h0, shiftedMantissa[30:23]};	
  wire        _GEN_1 = _GEN | (|(io_in_exp[7:3]));	
  wire        _GEN_2 = shiftedMantissa[22:0] == 23'h0;	
  wire [4:0]  _lzc_T_46 = shiftedMantissa[22] ? 5'h1 : shiftedMantissa[21] ? 5'h2 : shiftedMantissa[20] ? 5'h3 : shiftedMantissa[19] ? 5'h4 : shiftedMantissa[18] ? 5'h5 : shiftedMantissa[17] ? 5'h6 : shiftedMantissa[16] ? 5'h7 : shiftedMantissa[15] ? 5'h8 : shiftedMantissa[14] ? 5'h9 : shiftedMantissa[13] ? 5'hA : shiftedMantissa[12] ? 5'hB : shiftedMantissa[11] ? 5'hC : shiftedMantissa[10] ? 5'hD : shiftedMantissa[9] ? 5'hE : shiftedMantissa[8] ? 5'hF : shiftedMantissa[7] ? 5'h10 : shiftedMantissa[6] ? 5'h11 : shiftedMantissa[5] ? 5'h12 : shiftedMantissa[4] ? 5'h13 : shiftedMantissa[3] ? 5'h14 : shiftedMantissa[2] ? 5'h15 : {4'hB, ~(shiftedMantissa[1])};	
  wire [5:0]  _io_outRawFloat_exp_T_1 = 6'h0 - {1'h0, _lzc_T_46};	
  wire [53:0] _io_outRawFloat_mantissa_T = {31'h0, shiftedMantissa[22:0]} << _lzc_T_46;	
  assign io_outInt = _GEN_1 ? 9'h0 : io_in_sign ? 9'h0 - _GEN_0 : _GEN_0;	
  assign io_outFracMSBs = _GEN ? ($signed(_rightShiftAmt_T) < 9'sh3 ? fracAlignedToMinusOne[23:21] : 3'h0) : (|(io_in_exp[7:3])) ? 3'h0 : shiftedMantissa[22:20];	
  assign io_outRawFloat_isZero = ~_GEN_1 & _GEN_2 | io_in_isZero;	
  assign io_outRawFloat_isInf = ~_GEN & (|(io_in_exp[7:3])) | io_in_isInf;	
  assign io_outRawFloat_isNaN = io_in_isNaN;	
  assign io_outRawFloat_sign = io_in_sign;	
  assign io_outRawFloat_exp = _GEN_1 ? io_in_exp : _GEN_2 ? 9'h0 : {{3{_io_outRawFloat_exp_T_1[5]}}, _io_outRawFloat_exp_T_1};	
  assign io_outRawFloat_mantissa = _GEN_1 ? io_in_mantissa : _GEN_2 ? 24'h0 : _io_outRawFloat_mantissa_T[23:0];	
endmodule

