// Generated by CIRCT firtool-1.75.0
module RawFloat_MulAddExp2(	
  input         io_in_exp2,	
  input         io_in_a_isZero,	
  input         io_in_a_isInf,	
  input         io_in_a_isNaN,	
  input         io_in_a_sign,	
  input  [5:0]  io_in_a_exp,	
  input  [10:0] io_in_a_mantissa,	
  input         io_in_b_isZero,	
  input         io_in_b_isInf,	
  input         io_in_b_isNaN,	
  input         io_in_b_sign,	
  input  [5:0]  io_in_b_exp,	
  input  [10:0] io_in_b_mantissa,	
  input         io_in_c_isZero,	
  input         io_in_c_isInf,	
  input         io_in_c_isNaN,	
  input         io_in_c_sign,	
  input  [8:0]  io_in_c_exp,	
  input  [23:0] io_in_c_mantissa,	
  output        io_out_isZero,	
  output        io_out_isInf,	
  output        io_out_isNaN,	
  output        io_out_sign,	
  output [8:0]  io_out_exp,	
  output [25:0] io_out_mantissa,	
  output [2:0]  io_exp2_frac_msb	
);

  wire [5:0]  _split_io_outInt;	
  wire        _split_io_outRawFloat_isZero;	
  wire        _split_io_outRawFloat_isInf;	
  wire        _split_io_outRawFloat_isNaN;	
  wire        _split_io_outRawFloat_sign;	
  wire [5:0]  _split_io_outRawFloat_exp;	
  wire [10:0] _split_io_outRawFloat_mantissa;	
  wire        _fma_io_out_isZero;	
  wire        _fma_io_out_isInf;	
  wire        _fma_io_out_sign;	
  wire [8:0]  _fma_io_out_exp;	
  RawFloat_FMA_16 fma (	
    .io_a_isZero     (io_in_exp2 ? _split_io_outRawFloat_isZero : io_in_a_isZero),	
    .io_a_isInf      (io_in_exp2 ? _split_io_outRawFloat_isInf : io_in_a_isInf),	
    .io_a_isNaN      (io_in_exp2 ? _split_io_outRawFloat_isNaN : io_in_a_isNaN),	
    .io_a_sign       (io_in_exp2 ? _split_io_outRawFloat_sign : io_in_a_sign),	
    .io_a_exp        (io_in_exp2 ? _split_io_outRawFloat_exp : io_in_a_exp),	
    .io_a_mantissa   (io_in_exp2 ? _split_io_outRawFloat_mantissa : io_in_a_mantissa),	
    .io_b_isZero     (io_in_b_isZero),
    .io_b_isInf      (io_in_b_isInf),
    .io_b_isNaN      (io_in_b_isNaN),
    .io_b_sign       (io_in_b_sign),
    .io_b_exp        (io_in_b_exp),
    .io_b_mantissa   (io_in_b_mantissa),
    .io_c_isZero     (io_in_c_isZero),
    .io_c_isInf      (io_in_c_isInf),
    .io_c_isNaN      (io_in_c_isNaN),
    .io_c_sign       (io_in_c_sign),
    .io_c_exp        (io_in_c_exp),
    .io_c_mantissa   (io_in_c_mantissa),
    .io_out_isZero   (_fma_io_out_isZero),
    .io_out_isInf    (_fma_io_out_isInf),
    .io_out_isNaN    (io_out_isNaN),
    .io_out_sign     (_fma_io_out_sign),
    .io_out_exp      (_fma_io_out_exp),
    .io_out_mantissa (io_out_mantissa)
  );	
  RawFloat_SplitIF split (	
    .io_in_isZero            (io_in_a_isZero),
    .io_in_isInf             (io_in_a_isInf),
    .io_in_isNaN             (io_in_a_isNaN),
    .io_in_sign              (io_in_a_sign),
    .io_in_exp               (io_in_a_exp),
    .io_in_mantissa          (io_in_a_mantissa),
    .io_outInt               (_split_io_outInt),
    .io_outFracMSBs          (io_exp2_frac_msb),
    .io_outRawFloat_isZero   (_split_io_outRawFloat_isZero),
    .io_outRawFloat_isInf    (_split_io_outRawFloat_isInf),
    .io_outRawFloat_isNaN    (_split_io_outRawFloat_isNaN),
    .io_outRawFloat_sign     (_split_io_outRawFloat_sign),
    .io_outRawFloat_exp      (_split_io_outRawFloat_exp),
    .io_outRawFloat_mantissa (_split_io_outRawFloat_mantissa)
  );	
  assign io_out_isZero = io_in_exp2 ? _fma_io_out_isInf : _fma_io_out_isZero;	
  assign io_out_isInf = ~io_in_exp2 & _fma_io_out_isInf;	
  assign io_out_sign = ~io_in_exp2 & _fma_io_out_sign;	
  assign io_out_exp = io_in_exp2 ? {{3{_split_io_outInt[5]}}, _split_io_outInt} + _fma_io_out_exp : _fma_io_out_exp;	
endmodule

