// Generated by CIRCT firtool-1.75.0
module RawFloat_SplitIF(	
  input         io_in_isZero,	
  input         io_in_isInf,	
  input         io_in_isNaN,	
  input         io_in_sign,	
  input  [5:0]  io_in_exp,	
  input  [10:0] io_in_mantissa,	
  output [5:0]  io_outInt,	
  output [2:0]  io_outFracMSBs,	
  output        io_outRawFloat_isZero,	
  output        io_outRawFloat_isInf,	
  output        io_outRawFloat_isNaN,	
  output        io_outRawFloat_sign,	
  output [5:0]  io_outRawFloat_exp,	
  output [10:0] io_outRawFloat_mantissa	
);

  wire        _GEN = $signed(io_in_exp) < 6'sh0;	
  wire [5:0]  _rightShiftAmt_T = 6'h3F - io_in_exp;	
  wire [10:0] fracAlignedToMinusOne = io_in_mantissa >> _rightShiftAmt_T[1:0];	
  wire [17:0] _shiftedMantissa_T_1 = {7'h0, io_in_mantissa} << io_in_exp[2:0];	
  wire        _GEN_0 = io_in_exp[4:0] > 5'h4;	
  wire [5:0]  _GEN_1 = {1'h0, _shiftedMantissa_T_1[14:10]};	
  wire        _GEN_2 = _GEN | _GEN_0;	
  wire        _GEN_3 = _shiftedMantissa_T_1[9:0] == 10'h0;	
  wire [3:0]  _lzc_T_20 = _shiftedMantissa_T_1[9] ? 4'h1 : _shiftedMantissa_T_1[8] ? 4'h2 : _shiftedMantissa_T_1[7] ? 4'h3 : _shiftedMantissa_T_1[6] ? 4'h4 : _shiftedMantissa_T_1[5] ? 4'h5 : _shiftedMantissa_T_1[4] ? 4'h6 : _shiftedMantissa_T_1[3] ? 4'h7 : _shiftedMantissa_T_1[2] ? 4'h8 : _shiftedMantissa_T_1[1] ? 4'h9 : 4'hA;	
  wire [4:0]  _io_outRawFloat_exp_T_1 = 5'h0 - {1'h0, _lzc_T_20};	
  wire [24:0] _io_outRawFloat_mantissa_T = {15'h0, _shiftedMantissa_T_1[9:0]} << _lzc_T_20;	
  assign io_outInt = _GEN_2 ? 6'h0 : io_in_sign ? 6'h0 - _GEN_1 : _GEN_1;	
  assign io_outFracMSBs = _GEN ? ($signed(_rightShiftAmt_T) < 6'sh3 ? fracAlignedToMinusOne[10:8] : 3'h0) : _GEN_0 ? 3'h0 : _shiftedMantissa_T_1[9:7];	
  assign io_outRawFloat_isZero = ~_GEN_2 & _GEN_3 | io_in_isZero;	
  assign io_outRawFloat_isInf = ~_GEN & _GEN_0 | io_in_isInf;	
  assign io_outRawFloat_isNaN = io_in_isNaN;	
  assign io_outRawFloat_sign = io_in_sign;	
  assign io_outRawFloat_exp = _GEN_2 ? io_in_exp : _GEN_3 ? 6'h0 : {_io_outRawFloat_exp_T_1[4], _io_outRawFloat_exp_T_1};	
  assign io_outRawFloat_mantissa = _GEN_2 ? io_in_mantissa : _GEN_3 ? 11'h0 : _io_outRawFloat_mantissa_T[10:0];	
endmodule

