// Generated by CIRCT firtool-1.75.0
module ShiftRightJam(	
  input  [73:0] io_in,	
  input  [10:0] io_shamt,	
  output [73:0] io_out,	
  output        io_sticky	
);

  wire         exceed_max_shift = io_shamt > 11'h4A;	
  wire [127:0] _sticky_mask_T = 128'h1 << io_shamt[6:0];	
  assign io_out = exceed_max_shift ? 74'h0 : io_in >> io_shamt;	
  assign io_sticky = |(io_in & (_sticky_mask_T[73:0] - 74'h1 | {74{exceed_max_shift}}));	
endmodule

